/*
Copyright 2026 The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Command mock-virtualworkspace stands in for a virtual workspace server that is not kcp's own,
// so the e2e tests can exercise VirtualWorkspace.spec.command, spec.initContainers and the
// per-container kubeconfigs without depending on a real third-party server.
//
// It is a faithful stand-in in the ways the operator's contract can break:
//
//   - It declares exactly the flags the operator generates and nothing else. pflag exits on an
//     unknown flag, so if the operator ever passes a kcp-only argument to a custom server again,
//     this binary refuses to start and the pod never comes up.
//   - It serves TLS with the certificate the operator issued, on the port the operator chose.
//   - It connects to kcp with the kubeconfig it was given and reports, at /selfcheck, which
//     identity that turned out to be and what that identity may and may not do.
package main

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	"encoding/json"
	"encoding/pem"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"sort"
	"strings"
	"sync"
	"time"

	kcpcorev1alpha1 "github.com/kcp-dev/sdk/apis/core/v1alpha1"
	kcptenancyv1alpha1 "github.com/kcp-dev/sdk/apis/tenancy/v1alpha1"
	kcpclientset "github.com/kcp-dev/sdk/client/clientset/versioned"
	"github.com/spf13/pflag"

	corev1 "k8s.io/api/core/v1"
	rbacv1 "k8s.io/api/rbac/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/util/wait"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/rest"
	"k8s.io/client-go/tools/clientcmd"
	clientcmdapi "k8s.io/client-go/tools/clientcmd/api"
)

// options are the flags the operator generates for a virtual workspace, plus the few the mock
// needs of its own. Anything the operator passes that is not declared here is a bug in the
// operator, and pflag turns it into a non-zero exit.
type options struct {
	// TLS serving.
	tlsCertFile string
	tlsKeyFile  string
	bindAddress string
	securePort  int

	// Client authentication. Not used for serving decisions -- the mock only checks that the
	// files exist, which is enough to catch a broken CA mount.
	clientCAFile              string
	requestheaderClientCAFile string
	requestheaderAllowedNames []string
	requestheaderUsernames    []string
	requestheaderGroups       []string
	requestheaderExtraPrefix  []string

	// Connection to kcp.
	kubeconfig       string
	cacheKubeconfig  string
	shardExternalURL string

	// Mock-specific, passed through spec.extraArgs / an init container's args.
	mode           string
	workspace      string
	clusterRole    string
	probeConfigMap string
	bindUser       string
	verbosity      int
}

func main() {
	opts := &options{}
	fs := pflag.NewFlagSet("mock-virtualworkspace", pflag.ContinueOnError)

	// Generated by the operator for every virtual workspace.
	fs.StringVar(&opts.tlsCertFile, "tls-cert-file", "", "")
	fs.StringVar(&opts.tlsKeyFile, "tls-private-key-file", "", "")
	fs.StringVar(&opts.bindAddress, "bind-address", "0.0.0.0", "")
	fs.IntVar(&opts.securePort, "secure-port", 6443, "")
	fs.StringVar(&opts.clientCAFile, "client-ca-file", "", "")
	fs.StringVar(&opts.cacheKubeconfig, "cache-kubeconfig", "", "")
	fs.StringVar(&opts.shardExternalURL, "shard-external-url", "", "")
	fs.StringVar(&opts.requestheaderClientCAFile, "requestheader-client-ca-file", "", "")
	fs.StringSliceVar(&opts.requestheaderAllowedNames, "requestheader-allowed-names", nil, "")
	fs.StringSliceVar(&opts.requestheaderUsernames, "requestheader-username-headers", nil, "")
	fs.StringSliceVar(&opts.requestheaderGroups, "requestheader-group-headers", nil, "")
	fs.StringSliceVar(&opts.requestheaderExtraPrefix, "requestheader-extra-headers-prefix", nil, "")
	fs.StringVar(&opts.kubeconfig, "kubeconfig", "", "")
	fs.IntVarP(&opts.verbosity, "v", "v", 0, "")

	// The mock's own.
	fs.StringVar(&opts.mode, "mode", "serve", "either 'serve' or 'init'")
	fs.StringVar(&opts.workspace, "workspace", "mock", "workspace below root that init creates and serve works in")
	fs.StringVar(&opts.clusterRole, "cluster-role", "mock-vw", "ClusterRole init installs for the serving identity")
	fs.StringVar(&opts.probeConfigMap, "probe-configmap", "mock-probe", "ConfigMap init creates for serve to read back")
	fs.StringVar(&opts.bindUser, "bind-user", "", "user init binds to the ClusterRole; empty skips the binding")

	if err := fs.Parse(os.Args[1:]); err != nil {
		// Includes "unknown flag", which is the failure this binary exists to catch.
		fmt.Fprintf(os.Stderr, "mock-virtualworkspace: %v\n", err)
		os.Exit(2)
	}

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	var err error
	switch opts.mode {
	case "init":
		err = runInit(ctx, opts)
	case "serve":
		err = runServe(ctx, opts)
	default:
		err = fmt.Errorf("--mode must be 'serve' or 'init', got %q", opts.mode)
	}

	if err != nil {
		fmt.Fprintf(os.Stderr, "mock-virtualworkspace: %v\n", err)
		os.Exit(1)
	}
}

// runInit does the bootstrapping a custom virtual workspace would do before it can serve: create
// its own workspace, and inside it the ClusterRole the serving identity is bound to plus a
// ConfigMap for the server to read back. All of it needs administrative rights, so this failing is
// how the e2e test learns the init container did not get the credentials it was promised.
func runInit(ctx context.Context, opts *options) error {
	cfg, err := restConfig(opts.kubeconfig)
	if err != nil {
		return err
	}

	kcpClient, err := kcpclientset.NewForConfig(cfg)
	if err != nil {
		return fmt.Errorf("build kcp client: %w", err)
	}

	// The kubeconfig points at root, so this creates root:<workspace>.
	ws := &kcptenancyv1alpha1.Workspace{
		ObjectMeta: metav1.ObjectMeta{Name: opts.workspace},
		Spec: kcptenancyv1alpha1.WorkspaceSpec{
			Type: &kcptenancyv1alpha1.WorkspaceTypeReference{Name: "universal"},
		},
	}
	if _, err := kcpClient.TenancyV1alpha1().Workspaces().Create(ctx, ws, metav1.CreateOptions{}); err != nil && !apierrors.IsAlreadyExists(err) {
		return fmt.Errorf("create workspace %q: %w", opts.workspace, err)
	}

	fmt.Printf("waiting for workspace %q to become ready\n", opts.workspace)

	err = wait.PollUntilContextTimeout(ctx, time.Second, 3*time.Minute, true, func(ctx context.Context) (bool, error) {
		current, err := kcpClient.TenancyV1alpha1().Workspaces().Get(ctx, opts.workspace, metav1.GetOptions{})
		if err != nil {
			return false, nil
		}

		return current.Status.Phase == kcpcorev1alpha1.LogicalClusterPhaseReady, nil
	})
	if err != nil {
		return fmt.Errorf("waiting for workspace %q: %w", opts.workspace, err)
	}

	// Everything below lives inside the new workspace.
	inner, err := workspaceConfig(cfg, opts.workspace)
	if err != nil {
		return err
	}

	client, err := kubernetes.NewForConfig(inner)
	if err != nil {
		return fmt.Errorf("build client for workspace %q: %w", opts.workspace, err)
	}

	// What the serving identity is allowed to do: enter the workspace, and read ConfigMaps in
	// it. Nothing else.
	//
	// The verb=access rule on "/" is not optional. kcp gates every request on it before any
	// RBAC on the resource is consulted, so a role that grants only the resource permissions
	// leaves the identity unable to do anything at all. ServiceAccounts declared inside the
	// workspace are exempt, which is why a role written for one does not carry over to a user.
	role := &rbacv1.ClusterRole{
		ObjectMeta: metav1.ObjectMeta{Name: opts.clusterRole},
		Rules: []rbacv1.PolicyRule{
			{
				Verbs:           []string{"access"},
				NonResourceURLs: []string{"/"},
			},
			{
				APIGroups: []string{""},
				Resources: []string{"configmaps"},
				Verbs:     []string{"get", "list", "watch"},
			},
		},
	}
	if _, err := client.RbacV1().ClusterRoles().Create(ctx, role, metav1.CreateOptions{}); err != nil && !apierrors.IsAlreadyExists(err) {
		return fmt.Errorf("create ClusterRole %q: %w", opts.clusterRole, err)
	}

	// The binding is created here rather than through the Kubeconfig object's authorization
	// field, because that field's cleanup finalizer needs to reach kcp: if the shard or
	// front-proxy is deleted first, as happens when a whole namespace goes away, the Kubeconfig
	// can never be finalized and the namespace is stuck. A bootstrapper owns its own RBAC anyway.
	if opts.bindUser != "" {
		binding := &rbacv1.ClusterRoleBinding{
			ObjectMeta: metav1.ObjectMeta{Name: opts.clusterRole},
			RoleRef: rbacv1.RoleRef{
				APIGroup: rbacv1.GroupName,
				Kind:     "ClusterRole",
				Name:     opts.clusterRole,
			},
			Subjects: []rbacv1.Subject{{
				APIGroup: rbacv1.GroupName,
				Kind:     rbacv1.UserKind,
				Name:     opts.bindUser,
			}},
		}
		if _, err := client.RbacV1().ClusterRoleBindings().Create(ctx, binding, metav1.CreateOptions{}); err != nil && !apierrors.IsAlreadyExists(err) {
			return fmt.Errorf("create ClusterRoleBinding %q: %w", opts.clusterRole, err)
		}
	}

	probe := &corev1.ConfigMap{
		ObjectMeta: metav1.ObjectMeta{Name: opts.probeConfigMap, Namespace: "default"},
		Data:       map[string]string{"written-by": "init"},
	}
	if _, err := client.CoreV1().ConfigMaps("default").Create(ctx, probe, metav1.CreateOptions{}); err != nil && !apierrors.IsAlreadyExists(err) {
		return fmt.Errorf("create ConfigMap %q: %w", opts.probeConfigMap, err)
	}

	fmt.Printf("bootstrapped workspace %q as %s\n", opts.workspace, describeIdentity(opts.kubeconfig))

	return nil
}

// selfCheck is what the e2e test reads back from the running server.
type selfCheck struct {
	// Identity carried by the kubeconfig the server was given.
	User   string   `json:"user"`
	Groups []string `json:"groups"`

	// Whether the certificate and CA files the operator mounted are present and parseable.
	ServingCertLoaded bool `json:"servingCertLoaded"`
	ClientCALoaded    bool `json:"clientCALoaded"`
	RequestHeaderCA   bool `json:"requestHeaderCALoaded"`

	// What that identity turned out to be able to do in kcp.
	AllowedReadSucceeded bool `json:"allowedReadSucceeded"`
	ForbiddenWriteDenied bool `json:"forbiddenWriteDenied"`

	Errors []string `json:"errors,omitempty"`
}

// runServe serves a report on the credentials and mounts it was handed. Serving starts
// immediately and the checks against kcp run behind it, because those wait for RBAC to take
// effect and a server that listens only afterwards is indistinguishable from one that crashed.
// Until they finish, /selfcheck answers 503.
func runServe(ctx context.Context, opts *options) error {
	if opts.tlsCertFile == "" || opts.tlsKeyFile == "" {
		return errors.New("--tls-cert-file and --tls-private-key-file are required")
	}

	cert, err := tls.LoadX509KeyPair(opts.tlsCertFile, opts.tlsKeyFile)
	if err != nil {
		return fmt.Errorf("load serving certificate: %w", err)
	}

	result := selfCheck{
		ServingCertLoaded: true,
		ClientCALoaded:    fileHasCertificate(opts.clientCAFile),
		RequestHeaderCA:   fileHasCertificate(opts.requestheaderClientCAFile),
	}

	user, groups, err := identity(opts.kubeconfig)
	if err != nil {
		result.Errors = append(result.Errors, fmt.Sprintf("read identity: %v", err))
	}
	result.User, result.Groups = user, groups

	var (
		mu       sync.Mutex
		encoded  []byte
		complete bool
	)

	go func() {
		if err := checkPermissions(ctx, opts, &result); err != nil {
			result.Errors = append(result.Errors, err.Error())
		}

		body, err := json.MarshalIndent(result, "", "  ")
		if err != nil {
			body = []byte(fmt.Sprintf(`{"errors":[%q]}`, err.Error()))
		}

		mu.Lock()
		encoded, complete = body, true
		mu.Unlock()

		fmt.Printf("self check: %s\n", body)
	}()

	mux := http.NewServeMux()
	for _, path := range []string{"/healthz", "/readyz", "/livez"} {
		mux.HandleFunc(path, func(w http.ResponseWriter, _ *http.Request) {
			_, _ = io.WriteString(w, "ok\n")
		})
	}
	mux.HandleFunc("/selfcheck", func(w http.ResponseWriter, _ *http.Request) {
		mu.Lock()
		body, done := encoded, complete
		mu.Unlock()

		w.Header().Set("Content-Type", "application/json")
		if !done {
			w.WriteHeader(http.StatusServiceUnavailable)
			_, _ = io.WriteString(w, `{"status":"checks still running"}`)

			return
		}

		_, _ = w.Write(body)
	})

	server := &http.Server{
		Addr:              fmt.Sprintf("%s:%d", opts.bindAddress, opts.securePort),
		Handler:           mux,
		ReadHeaderTimeout: 10 * time.Second,
		TLSConfig:         &tls.Config{Certificates: []tls.Certificate{cert}, MinVersion: tls.VersionTLS12},
	}

	fmt.Printf("listening on %s\n", server.Addr)

	return server.ListenAndServeTLS("", "")
}

// checkPermissions establishes what the serving identity may do: it must be able to read the
// ConfigMap init left behind, and must not be able to write one. The negative half is the point --
// it is what distinguishes a properly scoped identity from an administrative one that merely
// happens to work.
func checkPermissions(ctx context.Context, opts *options, result *selfCheck) error {
	cfg, err := restConfig(opts.kubeconfig)
	if err != nil {
		return err
	}

	client, err := kubernetes.NewForConfig(cfg)
	if err != nil {
		return fmt.Errorf("build client: %w", err)
	}

	// kcp is eventually consistent about RBAC taking effect, so give the binding a moment. The
	// last failure is kept: without it a timeout here says only that the read never worked,
	// when what matters is whether it was denied, unreachable or something else entirely.
	var lastErr error

	err = wait.PollUntilContextTimeout(ctx, time.Second, 2*time.Minute, true, func(ctx context.Context) (bool, error) {
		_, lastErr = client.CoreV1().ConfigMaps("default").Get(ctx, opts.probeConfigMap, metav1.GetOptions{})
		return lastErr == nil, nil
	})
	if err != nil {
		return fmt.Errorf("reading ConfigMap %q was never permitted (last error: %v): %w", opts.probeConfigMap, lastErr, err)
	}
	result.AllowedReadSucceeded = true

	forbidden := &corev1.ConfigMap{
		ObjectMeta: metav1.ObjectMeta{Name: "mock-should-not-exist", Namespace: "default"},
	}
	if _, err := client.CoreV1().ConfigMaps("default").Create(ctx, forbidden, metav1.CreateOptions{}); err == nil {
		return errors.New("creating a ConfigMap succeeded, so the serving identity is not scoped")
	} else if !apierrors.IsForbidden(err) {
		return fmt.Errorf("creating a ConfigMap failed with %w, expected Forbidden", err)
	}
	result.ForbiddenWriteDenied = true

	return nil
}

func restConfig(kubeconfig string) (*rest.Config, error) {
	if kubeconfig == "" {
		return nil, errors.New("--kubeconfig is required")
	}

	cfg, err := clientcmd.BuildConfigFromFlags("", kubeconfig)
	if err != nil {
		return nil, fmt.Errorf("load kubeconfig %q: %w", kubeconfig, err)
	}

	return cfg, nil
}

// workspaceConfig retargets a config at a workspace below the one it currently points at.
func workspaceConfig(cfg *rest.Config, workspace string) (*rest.Config, error) {
	host := strings.TrimSuffix(cfg.Host, "/")

	if !strings.Contains(host, "/clusters/") {
		return nil, fmt.Errorf("kubeconfig server %q is not workspace scoped", cfg.Host)
	}

	out := rest.CopyConfig(cfg)
	out.Host = fmt.Sprintf("%s:%s", host, workspace)

	return out, nil
}

// identity reads the user and groups out of the client certificate a kubeconfig carries, rather
// than asking kcp, so the answer is what the operator handed this container even if the call to
// kcp fails.
func identity(kubeconfig string) (string, []string, error) {
	if kubeconfig == "" {
		return "", nil, errors.New("no kubeconfig")
	}

	config, err := clientcmd.LoadFromFile(kubeconfig)
	if err != nil {
		return "", nil, err
	}

	authInfo, err := currentAuthInfo(config)
	if err != nil {
		return "", nil, err
	}

	raw := authInfo.ClientCertificateData
	if len(raw) == 0 && authInfo.ClientCertificate != "" {
		if raw, err = os.ReadFile(authInfo.ClientCertificate); err != nil {
			return "", nil, err
		}
	}
	if len(raw) == 0 {
		return "", nil, errors.New("kubeconfig carries no client certificate")
	}

	block, _ := pem.Decode(raw)
	if block == nil {
		return "", nil, errors.New("client certificate is not PEM")
	}

	parsed, err := x509.ParseCertificate(block.Bytes)
	if err != nil {
		return "", nil, err
	}

	groups := append([]string(nil), parsed.Subject.Organization...)
	sort.Strings(groups)

	return parsed.Subject.CommonName, groups, nil
}

func currentAuthInfo(config *clientcmdapi.Config) (*clientcmdapi.AuthInfo, error) {
	kubeContext, ok := config.Contexts[config.CurrentContext]
	if !ok {
		return nil, fmt.Errorf("kubeconfig has no context %q", config.CurrentContext)
	}

	authInfo, ok := config.AuthInfos[kubeContext.AuthInfo]
	if !ok {
		return nil, fmt.Errorf("kubeconfig has no user %q", kubeContext.AuthInfo)
	}

	return authInfo, nil
}

func describeIdentity(kubeconfig string) string {
	user, groups, err := identity(kubeconfig)
	if err != nil {
		return fmt.Sprintf("<unknown: %v>", err)
	}

	return fmt.Sprintf("%s (groups: %s)", user, strings.Join(groups, ","))
}

func fileHasCertificate(path string) bool {
	if path == "" {
		return false
	}

	raw, err := os.ReadFile(path)
	if err != nil {
		return false
	}

	block, _ := pem.Decode(raw)

	return block != nil
}
