//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024 The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	kcpcache "github.com/kcp-dev/apimachinery/v2/pkg/cache"
	kcpinformers "github.com/kcp-dev/apimachinery/v2/third_party/informers"
	"github.com/kcp-dev/logicalcluster/v3"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/tools/cache"

	deployv1alpha1 "github.com/kcp-dev/kcp-operator/sdk/apis/deploy/v1alpha1"
	scopedclientset "github.com/kcp-dev/kcp-operator/sdk/clientset/versioned"
	clientset "github.com/kcp-dev/kcp-operator/sdk/clientset/versioned/cluster"
	"github.com/kcp-dev/kcp-operator/sdk/informers/externalversions/internalinterfaces"
	deployv1alpha1listers "github.com/kcp-dev/kcp-operator/sdk/listers/deploy/v1alpha1"
)

// CompiledFrontProxyClusterInformer provides access to a shared informer and lister for
// CompiledFrontProxies.
type CompiledFrontProxyClusterInformer interface {
	Cluster(logicalcluster.Name) CompiledFrontProxyInformer
	Informer() kcpcache.ScopeableSharedIndexInformer
	Lister() deployv1alpha1listers.CompiledFrontProxyClusterLister
}

type compiledFrontProxyClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewCompiledFrontProxyClusterInformer constructs a new informer for CompiledFrontProxy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCompiledFrontProxyClusterInformer(client clientset.ClusterInterface, resyncPeriod time.Duration, indexers cache.Indexers) kcpcache.ScopeableSharedIndexInformer {
	return NewFilteredCompiledFrontProxyClusterInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredCompiledFrontProxyClusterInformer constructs a new informer for CompiledFrontProxy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCompiledFrontProxyClusterInformer(client clientset.ClusterInterface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) kcpcache.ScopeableSharedIndexInformer {
	return kcpinformers.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DeployV1alpha1().CompiledFrontProxies().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DeployV1alpha1().CompiledFrontProxies().Watch(context.TODO(), options)
			},
		},
		&deployv1alpha1.CompiledFrontProxy{},
		resyncPeriod,
		indexers,
	)
}

func (f *compiledFrontProxyClusterInformer) defaultInformer(client clientset.ClusterInterface, resyncPeriod time.Duration) kcpcache.ScopeableSharedIndexInformer {
	return NewFilteredCompiledFrontProxyClusterInformer(client, resyncPeriod, cache.Indexers{
		kcpcache.ClusterIndexName:             kcpcache.ClusterIndexFunc,
		kcpcache.ClusterAndNamespaceIndexName: kcpcache.ClusterAndNamespaceIndexFunc},
		f.tweakListOptions,
	)
}

func (f *compiledFrontProxyClusterInformer) Informer() kcpcache.ScopeableSharedIndexInformer {
	return f.factory.InformerFor(&deployv1alpha1.CompiledFrontProxy{}, f.defaultInformer)
}

func (f *compiledFrontProxyClusterInformer) Lister() deployv1alpha1listers.CompiledFrontProxyClusterLister {
	return deployv1alpha1listers.NewCompiledFrontProxyClusterLister(f.Informer().GetIndexer())
}

// CompiledFrontProxyInformer provides access to a shared informer and lister for
// CompiledFrontProxies.
type CompiledFrontProxyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() deployv1alpha1listers.CompiledFrontProxyLister
}

func (f *compiledFrontProxyClusterInformer) Cluster(clusterName logicalcluster.Name) CompiledFrontProxyInformer {
	return &compiledFrontProxyInformer{
		informer: f.Informer().Cluster(clusterName),
		lister:   f.Lister().Cluster(clusterName),
	}
}

type compiledFrontProxyInformer struct {
	informer cache.SharedIndexInformer
	lister   deployv1alpha1listers.CompiledFrontProxyLister
}

func (f *compiledFrontProxyInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

func (f *compiledFrontProxyInformer) Lister() deployv1alpha1listers.CompiledFrontProxyLister {
	return f.lister
}

type compiledFrontProxyScopedInformer struct {
	factory          internalinterfaces.SharedScopedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

func (f *compiledFrontProxyScopedInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&deployv1alpha1.CompiledFrontProxy{}, f.defaultInformer)
}

func (f *compiledFrontProxyScopedInformer) Lister() deployv1alpha1listers.CompiledFrontProxyLister {
	return deployv1alpha1listers.NewCompiledFrontProxyLister(f.Informer().GetIndexer())
}

// NewCompiledFrontProxyInformer constructs a new informer for CompiledFrontProxy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCompiledFrontProxyInformer(client scopedclientset.Interface, resyncPeriod time.Duration, namespace string, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCompiledFrontProxyInformer(client, resyncPeriod, namespace, indexers, nil)
}

// NewFilteredCompiledFrontProxyInformer constructs a new informer for CompiledFrontProxy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCompiledFrontProxyInformer(client scopedclientset.Interface, resyncPeriod time.Duration, namespace string, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DeployV1alpha1().CompiledFrontProxies(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DeployV1alpha1().CompiledFrontProxies(namespace).Watch(context.TODO(), options)
			},
		},
		&deployv1alpha1.CompiledFrontProxy{},
		resyncPeriod,
		indexers,
	)
}

func (f *compiledFrontProxyScopedInformer) defaultInformer(client scopedclientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCompiledFrontProxyInformer(client, resyncPeriod, f.namespace, cache.Indexers{
		cache.NamespaceIndex: cache.MetaNamespaceIndexFunc,
	}, f.tweakListOptions)
}
