//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024 The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	kcpcache "github.com/kcp-dev/apimachinery/v2/pkg/cache"
	kcpinformers "github.com/kcp-dev/apimachinery/v2/third_party/informers"
	"github.com/kcp-dev/logicalcluster/v3"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/tools/cache"

	deployv1alpha1 "github.com/kcp-dev/kcp-operator/sdk/apis/deploy/v1alpha1"
	scopedclientset "github.com/kcp-dev/kcp-operator/sdk/clientset/versioned"
	clientset "github.com/kcp-dev/kcp-operator/sdk/clientset/versioned/cluster"
	"github.com/kcp-dev/kcp-operator/sdk/informers/externalversions/internalinterfaces"
	deployv1alpha1listers "github.com/kcp-dev/kcp-operator/sdk/listers/deploy/v1alpha1"
)

// CompiledRootShardClusterInformer provides access to a shared informer and lister for
// CompiledRootShards.
type CompiledRootShardClusterInformer interface {
	Cluster(logicalcluster.Name) CompiledRootShardInformer
	Informer() kcpcache.ScopeableSharedIndexInformer
	Lister() deployv1alpha1listers.CompiledRootShardClusterLister
}

type compiledRootShardClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewCompiledRootShardClusterInformer constructs a new informer for CompiledRootShard type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCompiledRootShardClusterInformer(client clientset.ClusterInterface, resyncPeriod time.Duration, indexers cache.Indexers) kcpcache.ScopeableSharedIndexInformer {
	return NewFilteredCompiledRootShardClusterInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredCompiledRootShardClusterInformer constructs a new informer for CompiledRootShard type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCompiledRootShardClusterInformer(client clientset.ClusterInterface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) kcpcache.ScopeableSharedIndexInformer {
	return kcpinformers.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DeployV1alpha1().CompiledRootShards().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DeployV1alpha1().CompiledRootShards().Watch(context.TODO(), options)
			},
		},
		&deployv1alpha1.CompiledRootShard{},
		resyncPeriod,
		indexers,
	)
}

func (f *compiledRootShardClusterInformer) defaultInformer(client clientset.ClusterInterface, resyncPeriod time.Duration) kcpcache.ScopeableSharedIndexInformer {
	return NewFilteredCompiledRootShardClusterInformer(client, resyncPeriod, cache.Indexers{
		kcpcache.ClusterIndexName:             kcpcache.ClusterIndexFunc,
		kcpcache.ClusterAndNamespaceIndexName: kcpcache.ClusterAndNamespaceIndexFunc},
		f.tweakListOptions,
	)
}

func (f *compiledRootShardClusterInformer) Informer() kcpcache.ScopeableSharedIndexInformer {
	return f.factory.InformerFor(&deployv1alpha1.CompiledRootShard{}, f.defaultInformer)
}

func (f *compiledRootShardClusterInformer) Lister() deployv1alpha1listers.CompiledRootShardClusterLister {
	return deployv1alpha1listers.NewCompiledRootShardClusterLister(f.Informer().GetIndexer())
}

// CompiledRootShardInformer provides access to a shared informer and lister for
// CompiledRootShards.
type CompiledRootShardInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() deployv1alpha1listers.CompiledRootShardLister
}

func (f *compiledRootShardClusterInformer) Cluster(clusterName logicalcluster.Name) CompiledRootShardInformer {
	return &compiledRootShardInformer{
		informer: f.Informer().Cluster(clusterName),
		lister:   f.Lister().Cluster(clusterName),
	}
}

type compiledRootShardInformer struct {
	informer cache.SharedIndexInformer
	lister   deployv1alpha1listers.CompiledRootShardLister
}

func (f *compiledRootShardInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

func (f *compiledRootShardInformer) Lister() deployv1alpha1listers.CompiledRootShardLister {
	return f.lister
}

type compiledRootShardScopedInformer struct {
	factory          internalinterfaces.SharedScopedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

func (f *compiledRootShardScopedInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&deployv1alpha1.CompiledRootShard{}, f.defaultInformer)
}

func (f *compiledRootShardScopedInformer) Lister() deployv1alpha1listers.CompiledRootShardLister {
	return deployv1alpha1listers.NewCompiledRootShardLister(f.Informer().GetIndexer())
}

// NewCompiledRootShardInformer constructs a new informer for CompiledRootShard type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCompiledRootShardInformer(client scopedclientset.Interface, resyncPeriod time.Duration, namespace string, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCompiledRootShardInformer(client, resyncPeriod, namespace, indexers, nil)
}

// NewFilteredCompiledRootShardInformer constructs a new informer for CompiledRootShard type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCompiledRootShardInformer(client scopedclientset.Interface, resyncPeriod time.Duration, namespace string, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DeployV1alpha1().CompiledRootShards(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DeployV1alpha1().CompiledRootShards(namespace).Watch(context.TODO(), options)
			},
		},
		&deployv1alpha1.CompiledRootShard{},
		resyncPeriod,
		indexers,
	)
}

func (f *compiledRootShardScopedInformer) defaultInformer(client scopedclientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCompiledRootShardInformer(client, resyncPeriod, f.namespace, cache.Indexers{
		cache.NamespaceIndex: cache.MetaNamespaceIndexFunc,
	}, f.tweakListOptions)
}
