//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024 The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	kcpcache "github.com/kcp-dev/apimachinery/v2/pkg/cache"
	kcpinformers "github.com/kcp-dev/apimachinery/v2/third_party/informers"
	"github.com/kcp-dev/logicalcluster/v3"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/tools/cache"

	deployv1alpha1 "github.com/kcp-dev/kcp-operator/sdk/apis/deploy/v1alpha1"
	scopedclientset "github.com/kcp-dev/kcp-operator/sdk/clientset/versioned"
	clientset "github.com/kcp-dev/kcp-operator/sdk/clientset/versioned/cluster"
	"github.com/kcp-dev/kcp-operator/sdk/informers/externalversions/internalinterfaces"
	deployv1alpha1listers "github.com/kcp-dev/kcp-operator/sdk/listers/deploy/v1alpha1"
)

// CompiledCacheServerClusterInformer provides access to a shared informer and lister for
// CompiledCacheServers.
type CompiledCacheServerClusterInformer interface {
	Cluster(logicalcluster.Name) CompiledCacheServerInformer
	Informer() kcpcache.ScopeableSharedIndexInformer
	Lister() deployv1alpha1listers.CompiledCacheServerClusterLister
}

type compiledCacheServerClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewCompiledCacheServerClusterInformer constructs a new informer for CompiledCacheServer type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCompiledCacheServerClusterInformer(client clientset.ClusterInterface, resyncPeriod time.Duration, indexers cache.Indexers) kcpcache.ScopeableSharedIndexInformer {
	return NewFilteredCompiledCacheServerClusterInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredCompiledCacheServerClusterInformer constructs a new informer for CompiledCacheServer type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCompiledCacheServerClusterInformer(client clientset.ClusterInterface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) kcpcache.ScopeableSharedIndexInformer {
	return kcpinformers.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DeployV1alpha1().CompiledCacheServers().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DeployV1alpha1().CompiledCacheServers().Watch(context.TODO(), options)
			},
		},
		&deployv1alpha1.CompiledCacheServer{},
		resyncPeriod,
		indexers,
	)
}

func (f *compiledCacheServerClusterInformer) defaultInformer(client clientset.ClusterInterface, resyncPeriod time.Duration) kcpcache.ScopeableSharedIndexInformer {
	return NewFilteredCompiledCacheServerClusterInformer(client, resyncPeriod, cache.Indexers{
		kcpcache.ClusterIndexName:             kcpcache.ClusterIndexFunc,
		kcpcache.ClusterAndNamespaceIndexName: kcpcache.ClusterAndNamespaceIndexFunc},
		f.tweakListOptions,
	)
}

func (f *compiledCacheServerClusterInformer) Informer() kcpcache.ScopeableSharedIndexInformer {
	return f.factory.InformerFor(&deployv1alpha1.CompiledCacheServer{}, f.defaultInformer)
}

func (f *compiledCacheServerClusterInformer) Lister() deployv1alpha1listers.CompiledCacheServerClusterLister {
	return deployv1alpha1listers.NewCompiledCacheServerClusterLister(f.Informer().GetIndexer())
}

// CompiledCacheServerInformer provides access to a shared informer and lister for
// CompiledCacheServers.
type CompiledCacheServerInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() deployv1alpha1listers.CompiledCacheServerLister
}

func (f *compiledCacheServerClusterInformer) Cluster(clusterName logicalcluster.Name) CompiledCacheServerInformer {
	return &compiledCacheServerInformer{
		informer: f.Informer().Cluster(clusterName),
		lister:   f.Lister().Cluster(clusterName),
	}
}

type compiledCacheServerInformer struct {
	informer cache.SharedIndexInformer
	lister   deployv1alpha1listers.CompiledCacheServerLister
}

func (f *compiledCacheServerInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

func (f *compiledCacheServerInformer) Lister() deployv1alpha1listers.CompiledCacheServerLister {
	return f.lister
}

type compiledCacheServerScopedInformer struct {
	factory          internalinterfaces.SharedScopedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

func (f *compiledCacheServerScopedInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&deployv1alpha1.CompiledCacheServer{}, f.defaultInformer)
}

func (f *compiledCacheServerScopedInformer) Lister() deployv1alpha1listers.CompiledCacheServerLister {
	return deployv1alpha1listers.NewCompiledCacheServerLister(f.Informer().GetIndexer())
}

// NewCompiledCacheServerInformer constructs a new informer for CompiledCacheServer type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCompiledCacheServerInformer(client scopedclientset.Interface, resyncPeriod time.Duration, namespace string, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCompiledCacheServerInformer(client, resyncPeriod, namespace, indexers, nil)
}

// NewFilteredCompiledCacheServerInformer constructs a new informer for CompiledCacheServer type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCompiledCacheServerInformer(client scopedclientset.Interface, resyncPeriod time.Duration, namespace string, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DeployV1alpha1().CompiledCacheServers(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DeployV1alpha1().CompiledCacheServers(namespace).Watch(context.TODO(), options)
			},
		},
		&deployv1alpha1.CompiledCacheServer{},
		resyncPeriod,
		indexers,
	)
}

func (f *compiledCacheServerScopedInformer) defaultInformer(client scopedclientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCompiledCacheServerInformer(client, resyncPeriod, f.namespace, cache.Indexers{
		cache.NamespaceIndex: cache.MetaNamespaceIndexFunc,
	}, f.tweakListOptions)
}
