//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024 The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	kcpcache "github.com/kcp-dev/apimachinery/v2/pkg/cache"
	kcpinformers "github.com/kcp-dev/apimachinery/v2/third_party/informers"
	"github.com/kcp-dev/logicalcluster/v3"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/tools/cache"

	deployv1alpha1 "github.com/kcp-dev/kcp-operator/sdk/apis/deploy/v1alpha1"
	scopedclientset "github.com/kcp-dev/kcp-operator/sdk/clientset/versioned"
	clientset "github.com/kcp-dev/kcp-operator/sdk/clientset/versioned/cluster"
	"github.com/kcp-dev/kcp-operator/sdk/informers/externalversions/internalinterfaces"
	deployv1alpha1listers "github.com/kcp-dev/kcp-operator/sdk/listers/deploy/v1alpha1"
)

// CompiledShardClusterInformer provides access to a shared informer and lister for
// CompiledShards.
type CompiledShardClusterInformer interface {
	Cluster(logicalcluster.Name) CompiledShardInformer
	Informer() kcpcache.ScopeableSharedIndexInformer
	Lister() deployv1alpha1listers.CompiledShardClusterLister
}

type compiledShardClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewCompiledShardClusterInformer constructs a new informer for CompiledShard type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCompiledShardClusterInformer(client clientset.ClusterInterface, resyncPeriod time.Duration, indexers cache.Indexers) kcpcache.ScopeableSharedIndexInformer {
	return NewFilteredCompiledShardClusterInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredCompiledShardClusterInformer constructs a new informer for CompiledShard type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCompiledShardClusterInformer(client clientset.ClusterInterface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) kcpcache.ScopeableSharedIndexInformer {
	return kcpinformers.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DeployV1alpha1().CompiledShards().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DeployV1alpha1().CompiledShards().Watch(context.TODO(), options)
			},
		},
		&deployv1alpha1.CompiledShard{},
		resyncPeriod,
		indexers,
	)
}

func (f *compiledShardClusterInformer) defaultInformer(client clientset.ClusterInterface, resyncPeriod time.Duration) kcpcache.ScopeableSharedIndexInformer {
	return NewFilteredCompiledShardClusterInformer(client, resyncPeriod, cache.Indexers{
		kcpcache.ClusterIndexName:             kcpcache.ClusterIndexFunc,
		kcpcache.ClusterAndNamespaceIndexName: kcpcache.ClusterAndNamespaceIndexFunc},
		f.tweakListOptions,
	)
}

func (f *compiledShardClusterInformer) Informer() kcpcache.ScopeableSharedIndexInformer {
	return f.factory.InformerFor(&deployv1alpha1.CompiledShard{}, f.defaultInformer)
}

func (f *compiledShardClusterInformer) Lister() deployv1alpha1listers.CompiledShardClusterLister {
	return deployv1alpha1listers.NewCompiledShardClusterLister(f.Informer().GetIndexer())
}

// CompiledShardInformer provides access to a shared informer and lister for
// CompiledShards.
type CompiledShardInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() deployv1alpha1listers.CompiledShardLister
}

func (f *compiledShardClusterInformer) Cluster(clusterName logicalcluster.Name) CompiledShardInformer {
	return &compiledShardInformer{
		informer: f.Informer().Cluster(clusterName),
		lister:   f.Lister().Cluster(clusterName),
	}
}

type compiledShardInformer struct {
	informer cache.SharedIndexInformer
	lister   deployv1alpha1listers.CompiledShardLister
}

func (f *compiledShardInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

func (f *compiledShardInformer) Lister() deployv1alpha1listers.CompiledShardLister {
	return f.lister
}

type compiledShardScopedInformer struct {
	factory          internalinterfaces.SharedScopedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

func (f *compiledShardScopedInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&deployv1alpha1.CompiledShard{}, f.defaultInformer)
}

func (f *compiledShardScopedInformer) Lister() deployv1alpha1listers.CompiledShardLister {
	return deployv1alpha1listers.NewCompiledShardLister(f.Informer().GetIndexer())
}

// NewCompiledShardInformer constructs a new informer for CompiledShard type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCompiledShardInformer(client scopedclientset.Interface, resyncPeriod time.Duration, namespace string, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCompiledShardInformer(client, resyncPeriod, namespace, indexers, nil)
}

// NewFilteredCompiledShardInformer constructs a new informer for CompiledShard type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCompiledShardInformer(client scopedclientset.Interface, resyncPeriod time.Duration, namespace string, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DeployV1alpha1().CompiledShards(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DeployV1alpha1().CompiledShards(namespace).Watch(context.TODO(), options)
			},
		},
		&deployv1alpha1.CompiledShard{},
		resyncPeriod,
		indexers,
	)
}

func (f *compiledShardScopedInformer) defaultInformer(client scopedclientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCompiledShardInformer(client, resyncPeriod, f.namespace, cache.Indexers{
		cache.NamespaceIndex: cache.MetaNamespaceIndexFunc,
	}, f.tweakListOptions)
}
