//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024 The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	"github.com/kcp-dev/kcp-operator/sdk/informers/externalversions/internalinterfaces"
)

type ClusterInterface interface {
	// CompiledCacheServers returns a CompiledCacheServerClusterInformer
	CompiledCacheServers() CompiledCacheServerClusterInformer
	// CompiledFrontProxies returns a CompiledFrontProxyClusterInformer
	CompiledFrontProxies() CompiledFrontProxyClusterInformer
	// CompiledRootShards returns a CompiledRootShardClusterInformer
	CompiledRootShards() CompiledRootShardClusterInformer
	// CompiledShards returns a CompiledShardClusterInformer
	CompiledShards() CompiledShardClusterInformer
	// CompiledVirtualWorkspaces returns a CompiledVirtualWorkspaceClusterInformer
	CompiledVirtualWorkspaces() CompiledVirtualWorkspaceClusterInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new ClusterInterface.
func New(f internalinterfaces.SharedInformerFactory, tweakListOptions internalinterfaces.TweakListOptionsFunc) ClusterInterface {
	return &version{factory: f, tweakListOptions: tweakListOptions}
}

// CompiledCacheServers returns a CompiledCacheServerClusterInformer
func (v *version) CompiledCacheServers() CompiledCacheServerClusterInformer {
	return &compiledCacheServerClusterInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// CompiledFrontProxies returns a CompiledFrontProxyClusterInformer
func (v *version) CompiledFrontProxies() CompiledFrontProxyClusterInformer {
	return &compiledFrontProxyClusterInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// CompiledRootShards returns a CompiledRootShardClusterInformer
func (v *version) CompiledRootShards() CompiledRootShardClusterInformer {
	return &compiledRootShardClusterInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// CompiledShards returns a CompiledShardClusterInformer
func (v *version) CompiledShards() CompiledShardClusterInformer {
	return &compiledShardClusterInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// CompiledVirtualWorkspaces returns a CompiledVirtualWorkspaceClusterInformer
func (v *version) CompiledVirtualWorkspaces() CompiledVirtualWorkspaceClusterInformer {
	return &compiledVirtualWorkspaceClusterInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

type Interface interface {
	// CompiledCacheServers returns a CompiledCacheServerInformer
	CompiledCacheServers() CompiledCacheServerInformer
	// CompiledFrontProxies returns a CompiledFrontProxyInformer
	CompiledFrontProxies() CompiledFrontProxyInformer
	// CompiledRootShards returns a CompiledRootShardInformer
	CompiledRootShards() CompiledRootShardInformer
	// CompiledShards returns a CompiledShardInformer
	CompiledShards() CompiledShardInformer
	// CompiledVirtualWorkspaces returns a CompiledVirtualWorkspaceInformer
	CompiledVirtualWorkspaces() CompiledVirtualWorkspaceInformer
}

type scopedVersion struct {
	factory          internalinterfaces.SharedScopedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// New returns a new ClusterInterface.
func NewScoped(f internalinterfaces.SharedScopedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &scopedVersion{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// CompiledCacheServers returns a CompiledCacheServerInformer
func (v *scopedVersion) CompiledCacheServers() CompiledCacheServerInformer {
	return &compiledCacheServerScopedInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// CompiledFrontProxies returns a CompiledFrontProxyInformer
func (v *scopedVersion) CompiledFrontProxies() CompiledFrontProxyInformer {
	return &compiledFrontProxyScopedInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// CompiledRootShards returns a CompiledRootShardInformer
func (v *scopedVersion) CompiledRootShards() CompiledRootShardInformer {
	return &compiledRootShardScopedInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// CompiledShards returns a CompiledShardInformer
func (v *scopedVersion) CompiledShards() CompiledShardInformer {
	return &compiledShardScopedInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// CompiledVirtualWorkspaces returns a CompiledVirtualWorkspaceInformer
func (v *scopedVersion) CompiledVirtualWorkspaces() CompiledVirtualWorkspaceInformer {
	return &compiledVirtualWorkspaceScopedInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
