---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  - issuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deploy.operator.kcp.io
  resources:
  - compiledcacheservers
  - compiledfrontproxies
  - compiledrootshards
  - compiledshards
  - compiledvirtualworkspaces
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deploy.operator.kcp.io
  resources:
  - compiledcacheservers/finalizers
  - compiledfrontproxies/finalizers
  - compiledrootshards/finalizers
  - compiledshards/finalizers
  - compiledvirtualworkspaces/finalizers
  verbs:
  - update
- apiGroups:
  - deploy.operator.kcp.io
  resources:
  - compiledfrontproxies/status
  - compiledrootshards/status
  - compiledshards/status
  - compiledvirtualworkspaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operator.kcp.io
  resources:
  - cacheservers
  - frontproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.kcp.io
  resources:
  - cacheservers/finalizers
  - frontproxies/finalizers
  - kubeconfigs/finalizers
  - rootshards/finalizers
  - shards/finalizers
  verbs:
  - update
- apiGroups:
  - operator.kcp.io
  resources:
  - cacheservers/status
  - frontproxies/status
  - kubeconfigs/status
  - rootshards/status
  - shards/status
  - virtualworkspaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operator.kcp.io
  resources:
  - kubeconfigs
  - rootshards
  - shards
  - virtualworkspaces
  verbs:
  - get
  - list
  - patch
  - update
  - watch
