/*
Copyright 2024 The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen-v0.32. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"

	deployv1alpha1 "github.com/kcp-dev/kcp-operator/sdk/apis/deploy/v1alpha1"
	scheme "github.com/kcp-dev/kcp-operator/sdk/clientset/versioned/scheme"
)

// CompiledRootShardsGetter has a method to return a CompiledRootShardInterface.
// A group's client should implement this interface.
type CompiledRootShardsGetter interface {
	CompiledRootShards(namespace string) CompiledRootShardInterface
}

// CompiledRootShardInterface has methods to work with CompiledRootShard resources.
type CompiledRootShardInterface interface {
	Create(ctx context.Context, compiledRootShard *deployv1alpha1.CompiledRootShard, opts v1.CreateOptions) (*deployv1alpha1.CompiledRootShard, error)
	Update(ctx context.Context, compiledRootShard *deployv1alpha1.CompiledRootShard, opts v1.UpdateOptions) (*deployv1alpha1.CompiledRootShard, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, compiledRootShard *deployv1alpha1.CompiledRootShard, opts v1.UpdateOptions) (*deployv1alpha1.CompiledRootShard, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*deployv1alpha1.CompiledRootShard, error)
	List(ctx context.Context, opts v1.ListOptions) (*deployv1alpha1.CompiledRootShardList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *deployv1alpha1.CompiledRootShard, err error)
	CompiledRootShardExpansion
}

// compiledRootShards implements CompiledRootShardInterface
type compiledRootShards struct {
	*gentype.ClientWithList[*deployv1alpha1.CompiledRootShard, *deployv1alpha1.CompiledRootShardList]
}

// newCompiledRootShards returns a CompiledRootShards
func newCompiledRootShards(c *DeployV1alpha1Client, namespace string) *compiledRootShards {
	return &compiledRootShards{
		gentype.NewClientWithList[*deployv1alpha1.CompiledRootShard, *deployv1alpha1.CompiledRootShardList](
			"compiledrootshards",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *deployv1alpha1.CompiledRootShard { return &deployv1alpha1.CompiledRootShard{} },
			func() *deployv1alpha1.CompiledRootShardList { return &deployv1alpha1.CompiledRootShardList{} },
		),
	}
}
