/*
Copyright 2024 The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen-v0.32. DO NOT EDIT.

package v1alpha1

import (
	http "net/http"

	rest "k8s.io/client-go/rest"

	deployv1alpha1 "github.com/kcp-dev/kcp-operator/sdk/apis/deploy/v1alpha1"
	scheme "github.com/kcp-dev/kcp-operator/sdk/clientset/versioned/scheme"
)

type DeployV1alpha1Interface interface {
	RESTClient() rest.Interface
	CompiledCacheServersGetter
	CompiledFrontProxiesGetter
	CompiledRootShardsGetter
	CompiledShardsGetter
	CompiledVirtualWorkspacesGetter
}

// DeployV1alpha1Client is used to interact with features provided by the deploy.operator.kcp.io group.
type DeployV1alpha1Client struct {
	restClient rest.Interface
}

func (c *DeployV1alpha1Client) CompiledCacheServers(namespace string) CompiledCacheServerInterface {
	return newCompiledCacheServers(c, namespace)
}

func (c *DeployV1alpha1Client) CompiledFrontProxies(namespace string) CompiledFrontProxyInterface {
	return newCompiledFrontProxies(c, namespace)
}

func (c *DeployV1alpha1Client) CompiledRootShards(namespace string) CompiledRootShardInterface {
	return newCompiledRootShards(c, namespace)
}

func (c *DeployV1alpha1Client) CompiledShards(namespace string) CompiledShardInterface {
	return newCompiledShards(c, namespace)
}

func (c *DeployV1alpha1Client) CompiledVirtualWorkspaces(namespace string) CompiledVirtualWorkspaceInterface {
	return newCompiledVirtualWorkspaces(c, namespace)
}

// NewForConfig creates a new DeployV1alpha1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*DeployV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new DeployV1alpha1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*DeployV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &DeployV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new DeployV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *DeployV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new DeployV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *DeployV1alpha1Client {
	return &DeployV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := deployv1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = rest.CodecFactoryForGeneratedClient(scheme.Scheme, scheme.Codecs).WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *DeployV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
