/*
Copyright 2024 The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen-v0.32. DO NOT EDIT.

package v1alpha1

import (
	operatorv1alpha1 "github.com/kcp-dev/kcp-operator/sdk/applyconfiguration/operator/v1alpha1"
)

// CompiledVirtualWorkspaceSpecApplyConfiguration represents a declarative configuration of the CompiledVirtualWorkspaceSpec type for use
// with apply.
type CompiledVirtualWorkspaceSpecApplyConfiguration struct {
	VirtualWorkspace *operatorv1alpha1.VirtualWorkspaceSpecApplyConfiguration `json:"virtualWorkspace,omitempty"`
	RootShard        *NamedRootShardSpecApplyConfiguration                    `json:"rootShard,omitempty"`
	Shard            *NamedShardSpecApplyConfiguration                        `json:"shard,omitempty"`
}

// CompiledVirtualWorkspaceSpecApplyConfiguration constructs a declarative configuration of the CompiledVirtualWorkspaceSpec type for use with
// apply.
func CompiledVirtualWorkspaceSpec() *CompiledVirtualWorkspaceSpecApplyConfiguration {
	return &CompiledVirtualWorkspaceSpecApplyConfiguration{}
}

// WithVirtualWorkspace sets the VirtualWorkspace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VirtualWorkspace field is set to the value of the last call.
func (b *CompiledVirtualWorkspaceSpecApplyConfiguration) WithVirtualWorkspace(value *operatorv1alpha1.VirtualWorkspaceSpecApplyConfiguration) *CompiledVirtualWorkspaceSpecApplyConfiguration {
	b.VirtualWorkspace = value
	return b
}

// WithRootShard sets the RootShard field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RootShard field is set to the value of the last call.
func (b *CompiledVirtualWorkspaceSpecApplyConfiguration) WithRootShard(value *NamedRootShardSpecApplyConfiguration) *CompiledVirtualWorkspaceSpecApplyConfiguration {
	b.RootShard = value
	return b
}

// WithShard sets the Shard field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Shard field is set to the value of the last call.
func (b *CompiledVirtualWorkspaceSpecApplyConfiguration) WithShard(value *NamedShardSpecApplyConfiguration) *CompiledVirtualWorkspaceSpecApplyConfiguration {
	b.Shard = value
	return b
}
