/*
Copyright 2024 The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen-v0.32. DO NOT EDIT.

package v1alpha1

import (
	operatorv1alpha1 "github.com/kcp-dev/kcp-operator/sdk/applyconfiguration/operator/v1alpha1"
)

// CompiledShardSpecApplyConfiguration represents a declarative configuration of the CompiledShardSpec type for use
// with apply.
type CompiledShardSpecApplyConfiguration struct {
	Shard            *operatorv1alpha1.ShardSpecApplyConfiguration `json:"shard,omitempty"`
	RootShard        *NamedRootShardSpecApplyConfiguration         `json:"rootShard,omitempty"`
	VirtualWorkspace *NamedVirtualWorkspaceSpecApplyConfiguration  `json:"virtualWorkspace,omitempty"`
	Shards           []string                                      `json:"shards,omitempty"`
}

// CompiledShardSpecApplyConfiguration constructs a declarative configuration of the CompiledShardSpec type for use with
// apply.
func CompiledShardSpec() *CompiledShardSpecApplyConfiguration {
	return &CompiledShardSpecApplyConfiguration{}
}

// WithShard sets the Shard field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Shard field is set to the value of the last call.
func (b *CompiledShardSpecApplyConfiguration) WithShard(value *operatorv1alpha1.ShardSpecApplyConfiguration) *CompiledShardSpecApplyConfiguration {
	b.Shard = value
	return b
}

// WithRootShard sets the RootShard field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RootShard field is set to the value of the last call.
func (b *CompiledShardSpecApplyConfiguration) WithRootShard(value *NamedRootShardSpecApplyConfiguration) *CompiledShardSpecApplyConfiguration {
	b.RootShard = value
	return b
}

// WithVirtualWorkspace sets the VirtualWorkspace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VirtualWorkspace field is set to the value of the last call.
func (b *CompiledShardSpecApplyConfiguration) WithVirtualWorkspace(value *NamedVirtualWorkspaceSpecApplyConfiguration) *CompiledShardSpecApplyConfiguration {
	b.VirtualWorkspace = value
	return b
}

// WithShards adds the given value to the Shards field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Shards field.
func (b *CompiledShardSpecApplyConfiguration) WithShards(values ...string) *CompiledShardSpecApplyConfiguration {
	for i := range values {
		b.Shards = append(b.Shards, values[i])
	}
	return b
}
