/*
Copyright 2024 The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen-v0.32. DO NOT EDIT.

package v1alpha1

import (
	operatorv1alpha1 "github.com/kcp-dev/kcp-operator/sdk/applyconfiguration/operator/v1alpha1"
)

// NamedShardSpecApplyConfiguration represents a declarative configuration of the NamedShardSpec type for use
// with apply.
type NamedShardSpecApplyConfiguration struct {
	Name *string                                       `json:"name,omitempty"`
	Spec *operatorv1alpha1.ShardSpecApplyConfiguration `json:"spec,omitempty"`
}

// NamedShardSpecApplyConfiguration constructs a declarative configuration of the NamedShardSpec type for use with
// apply.
func NamedShardSpec() *NamedShardSpecApplyConfiguration {
	return &NamedShardSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *NamedShardSpecApplyConfiguration) WithName(value string) *NamedShardSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *NamedShardSpecApplyConfiguration) WithSpec(value *operatorv1alpha1.ShardSpecApplyConfiguration) *NamedShardSpecApplyConfiguration {
	b.Spec = value
	return b
}
