/*
Copyright 2024 The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen-v0.32. DO NOT EDIT.

package fake

import (
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"

	v1alpha1 "github.com/kcp-dev/kcp-operator/sdk/clientset/versioned/typed/deploy/v1alpha1"
)

type FakeDeployV1alpha1 struct {
	*testing.Fake
}

func (c *FakeDeployV1alpha1) CompiledCacheServers(namespace string) v1alpha1.CompiledCacheServerInterface {
	return newFakeCompiledCacheServers(c, namespace)
}

func (c *FakeDeployV1alpha1) CompiledFrontProxies(namespace string) v1alpha1.CompiledFrontProxyInterface {
	return newFakeCompiledFrontProxies(c, namespace)
}

func (c *FakeDeployV1alpha1) CompiledRootShards(namespace string) v1alpha1.CompiledRootShardInterface {
	return newFakeCompiledRootShards(c, namespace)
}

func (c *FakeDeployV1alpha1) CompiledShards(namespace string) v1alpha1.CompiledShardInterface {
	return newFakeCompiledShards(c, namespace)
}

func (c *FakeDeployV1alpha1) CompiledVirtualWorkspaces(namespace string) v1alpha1.CompiledVirtualWorkspaceInterface {
	return newFakeCompiledVirtualWorkspaces(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeDeployV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
