/*
Copyright 2024 The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen-v0.32. DO NOT EDIT.

package fake

import (
	gentype "k8s.io/client-go/gentype"

	v1alpha1 "github.com/kcp-dev/kcp-operator/sdk/apis/deploy/v1alpha1"
	deployv1alpha1 "github.com/kcp-dev/kcp-operator/sdk/clientset/versioned/typed/deploy/v1alpha1"
)

// fakeCompiledVirtualWorkspaces implements CompiledVirtualWorkspaceInterface
type fakeCompiledVirtualWorkspaces struct {
	*gentype.FakeClientWithList[*v1alpha1.CompiledVirtualWorkspace, *v1alpha1.CompiledVirtualWorkspaceList]
	Fake *FakeDeployV1alpha1
}

func newFakeCompiledVirtualWorkspaces(fake *FakeDeployV1alpha1, namespace string) deployv1alpha1.CompiledVirtualWorkspaceInterface {
	return &fakeCompiledVirtualWorkspaces{
		gentype.NewFakeClientWithList[*v1alpha1.CompiledVirtualWorkspace, *v1alpha1.CompiledVirtualWorkspaceList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("compiledvirtualworkspaces"),
			v1alpha1.SchemeGroupVersion.WithKind("CompiledVirtualWorkspace"),
			func() *v1alpha1.CompiledVirtualWorkspace { return &v1alpha1.CompiledVirtualWorkspace{} },
			func() *v1alpha1.CompiledVirtualWorkspaceList { return &v1alpha1.CompiledVirtualWorkspaceList{} },
			func(dst, src *v1alpha1.CompiledVirtualWorkspaceList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.CompiledVirtualWorkspaceList) []*v1alpha1.CompiledVirtualWorkspace {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.CompiledVirtualWorkspaceList, items []*v1alpha1.CompiledVirtualWorkspace) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
