//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompiledCacheServer) DeepCopyInto(out *CompiledCacheServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompiledCacheServer.
func (in *CompiledCacheServer) DeepCopy() *CompiledCacheServer {
	if in == nil {
		return nil
	}
	out := new(CompiledCacheServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CompiledCacheServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompiledCacheServerList) DeepCopyInto(out *CompiledCacheServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CompiledCacheServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompiledCacheServerList.
func (in *CompiledCacheServerList) DeepCopy() *CompiledCacheServerList {
	if in == nil {
		return nil
	}
	out := new(CompiledCacheServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CompiledCacheServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompiledCacheServerSpec) DeepCopyInto(out *CompiledCacheServerSpec) {
	*out = *in
	in.CacheServer.DeepCopyInto(&out.CacheServer)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompiledCacheServerSpec.
func (in *CompiledCacheServerSpec) DeepCopy() *CompiledCacheServerSpec {
	if in == nil {
		return nil
	}
	out := new(CompiledCacheServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompiledFrontProxy) DeepCopyInto(out *CompiledFrontProxy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompiledFrontProxy.
func (in *CompiledFrontProxy) DeepCopy() *CompiledFrontProxy {
	if in == nil {
		return nil
	}
	out := new(CompiledFrontProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CompiledFrontProxy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompiledFrontProxyList) DeepCopyInto(out *CompiledFrontProxyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CompiledFrontProxy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompiledFrontProxyList.
func (in *CompiledFrontProxyList) DeepCopy() *CompiledFrontProxyList {
	if in == nil {
		return nil
	}
	out := new(CompiledFrontProxyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CompiledFrontProxyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompiledFrontProxySpec) DeepCopyInto(out *CompiledFrontProxySpec) {
	*out = *in
	in.FrontProxy.DeepCopyInto(&out.FrontProxy)
	in.RootShard.DeepCopyInto(&out.RootShard)
	if in.Shards != nil {
		in, out := &in.Shards, &out.Shards
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompiledFrontProxySpec.
func (in *CompiledFrontProxySpec) DeepCopy() *CompiledFrontProxySpec {
	if in == nil {
		return nil
	}
	out := new(CompiledFrontProxySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompiledRootShard) DeepCopyInto(out *CompiledRootShard) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompiledRootShard.
func (in *CompiledRootShard) DeepCopy() *CompiledRootShard {
	if in == nil {
		return nil
	}
	out := new(CompiledRootShard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CompiledRootShard) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompiledRootShardList) DeepCopyInto(out *CompiledRootShardList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CompiledRootShard, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompiledRootShardList.
func (in *CompiledRootShardList) DeepCopy() *CompiledRootShardList {
	if in == nil {
		return nil
	}
	out := new(CompiledRootShardList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CompiledRootShardList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompiledRootShardSpec) DeepCopyInto(out *CompiledRootShardSpec) {
	*out = *in
	in.RootShard.DeepCopyInto(&out.RootShard)
	if in.VirtualWorkspace != nil {
		in, out := &in.VirtualWorkspace, &out.VirtualWorkspace
		*out = new(NamedVirtualWorkspaceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Shards != nil {
		in, out := &in.Shards, &out.Shards
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompiledRootShardSpec.
func (in *CompiledRootShardSpec) DeepCopy() *CompiledRootShardSpec {
	if in == nil {
		return nil
	}
	out := new(CompiledRootShardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompiledShard) DeepCopyInto(out *CompiledShard) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompiledShard.
func (in *CompiledShard) DeepCopy() *CompiledShard {
	if in == nil {
		return nil
	}
	out := new(CompiledShard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CompiledShard) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompiledShardList) DeepCopyInto(out *CompiledShardList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CompiledShard, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompiledShardList.
func (in *CompiledShardList) DeepCopy() *CompiledShardList {
	if in == nil {
		return nil
	}
	out := new(CompiledShardList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CompiledShardList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompiledShardSpec) DeepCopyInto(out *CompiledShardSpec) {
	*out = *in
	in.Shard.DeepCopyInto(&out.Shard)
	in.RootShard.DeepCopyInto(&out.RootShard)
	if in.VirtualWorkspace != nil {
		in, out := &in.VirtualWorkspace, &out.VirtualWorkspace
		*out = new(NamedVirtualWorkspaceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Shards != nil {
		in, out := &in.Shards, &out.Shards
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompiledShardSpec.
func (in *CompiledShardSpec) DeepCopy() *CompiledShardSpec {
	if in == nil {
		return nil
	}
	out := new(CompiledShardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompiledVirtualWorkspace) DeepCopyInto(out *CompiledVirtualWorkspace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompiledVirtualWorkspace.
func (in *CompiledVirtualWorkspace) DeepCopy() *CompiledVirtualWorkspace {
	if in == nil {
		return nil
	}
	out := new(CompiledVirtualWorkspace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CompiledVirtualWorkspace) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompiledVirtualWorkspaceList) DeepCopyInto(out *CompiledVirtualWorkspaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CompiledVirtualWorkspace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompiledVirtualWorkspaceList.
func (in *CompiledVirtualWorkspaceList) DeepCopy() *CompiledVirtualWorkspaceList {
	if in == nil {
		return nil
	}
	out := new(CompiledVirtualWorkspaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CompiledVirtualWorkspaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompiledVirtualWorkspaceSpec) DeepCopyInto(out *CompiledVirtualWorkspaceSpec) {
	*out = *in
	in.VirtualWorkspace.DeepCopyInto(&out.VirtualWorkspace)
	in.RootShard.DeepCopyInto(&out.RootShard)
	if in.Shard != nil {
		in, out := &in.Shard, &out.Shard
		*out = new(NamedShardSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompiledVirtualWorkspaceSpec.
func (in *CompiledVirtualWorkspaceSpec) DeepCopy() *CompiledVirtualWorkspaceSpec {
	if in == nil {
		return nil
	}
	out := new(CompiledVirtualWorkspaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamedRootShardSpec) DeepCopyInto(out *NamedRootShardSpec) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamedRootShardSpec.
func (in *NamedRootShardSpec) DeepCopy() *NamedRootShardSpec {
	if in == nil {
		return nil
	}
	out := new(NamedRootShardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamedShardSpec) DeepCopyInto(out *NamedShardSpec) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamedShardSpec.
func (in *NamedShardSpec) DeepCopy() *NamedShardSpec {
	if in == nil {
		return nil
	}
	out := new(NamedShardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamedVirtualWorkspaceSpec) DeepCopyInto(out *NamedVirtualWorkspaceSpec) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamedVirtualWorkspaceSpec.
func (in *NamedVirtualWorkspaceSpec) DeepCopy() *NamedVirtualWorkspaceSpec {
	if in == nil {
		return nil
	}
	out := new(NamedVirtualWorkspaceSpec)
	in.DeepCopyInto(out)
	return out
}
