//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024 The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	kcpcache "github.com/kcp-dev/apimachinery/v2/pkg/cache"
	"github.com/kcp-dev/logicalcluster/v3"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"

	deployv1alpha1 "github.com/kcp-dev/kcp-operator/sdk/apis/deploy/v1alpha1"
)

// CompiledShardClusterLister can list CompiledShards across all workspaces, or scope down to a CompiledShardLister for one workspace.
// All objects returned here must be treated as read-only.
type CompiledShardClusterLister interface {
	// List lists all CompiledShards in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*deployv1alpha1.CompiledShard, err error)
	// Cluster returns a lister that can list and get CompiledShards in one workspace.
	Cluster(clusterName logicalcluster.Name) CompiledShardLister
	CompiledShardClusterListerExpansion
}

type compiledShardClusterLister struct {
	indexer cache.Indexer
}

// NewCompiledShardClusterLister returns a new CompiledShardClusterLister.
// We assume that the indexer:
// - is fed by a cross-workspace LIST+WATCH
// - uses kcpcache.MetaClusterNamespaceKeyFunc as the key function
// - has the kcpcache.ClusterIndex as an index
// - has the kcpcache.ClusterAndNamespaceIndex as an index
func NewCompiledShardClusterLister(indexer cache.Indexer) *compiledShardClusterLister {
	return &compiledShardClusterLister{indexer: indexer}
}

// List lists all CompiledShards in the indexer across all workspaces.
func (s *compiledShardClusterLister) List(selector labels.Selector) (ret []*deployv1alpha1.CompiledShard, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*deployv1alpha1.CompiledShard))
	})
	return ret, err
}

// Cluster scopes the lister to one workspace, allowing users to list and get CompiledShards.
func (s *compiledShardClusterLister) Cluster(clusterName logicalcluster.Name) CompiledShardLister {
	return &compiledShardLister{indexer: s.indexer, clusterName: clusterName}
}

// CompiledShardLister can list CompiledShards across all namespaces, or scope down to a CompiledShardNamespaceLister for one namespace.
// All objects returned here must be treated as read-only.
type CompiledShardLister interface {
	// List lists all CompiledShards in the workspace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*deployv1alpha1.CompiledShard, err error)
	// CompiledShards returns a lister that can list and get CompiledShards in one workspace and namespace.
	CompiledShards(namespace string) CompiledShardNamespaceLister
	CompiledShardListerExpansion
}

// compiledShardLister can list all CompiledShards inside a workspace or scope down to a CompiledShardLister for one namespace.
type compiledShardLister struct {
	indexer     cache.Indexer
	clusterName logicalcluster.Name
}

// List lists all CompiledShards in the indexer for a workspace.
func (s *compiledShardLister) List(selector labels.Selector) (ret []*deployv1alpha1.CompiledShard, err error) {
	err = kcpcache.ListAllByCluster(s.indexer, s.clusterName, selector, func(i interface{}) {
		ret = append(ret, i.(*deployv1alpha1.CompiledShard))
	})
	return ret, err
}

// CompiledShards returns an object that can list and get CompiledShards in one namespace.
func (s *compiledShardLister) CompiledShards(namespace string) CompiledShardNamespaceLister {
	return &compiledShardNamespaceLister{indexer: s.indexer, clusterName: s.clusterName, namespace: namespace}
}

// compiledShardNamespaceLister helps list and get CompiledShards.
// All objects returned here must be treated as read-only.
type CompiledShardNamespaceLister interface {
	// List lists all CompiledShards in the workspace and namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*deployv1alpha1.CompiledShard, err error)
	// Get retrieves the CompiledShard from the indexer for a given workspace, namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*deployv1alpha1.CompiledShard, error)
	CompiledShardNamespaceListerExpansion
}

// compiledShardNamespaceLister helps list and get CompiledShards.
// All objects returned here must be treated as read-only.
type compiledShardNamespaceLister struct {
	indexer     cache.Indexer
	clusterName logicalcluster.Name
	namespace   string
}

// List lists all CompiledShards in the indexer for a given workspace and namespace.
func (s *compiledShardNamespaceLister) List(selector labels.Selector) (ret []*deployv1alpha1.CompiledShard, err error) {
	err = kcpcache.ListAllByClusterAndNamespace(s.indexer, s.clusterName, s.namespace, selector, func(i interface{}) {
		ret = append(ret, i.(*deployv1alpha1.CompiledShard))
	})
	return ret, err
}

// Get retrieves the CompiledShard from the indexer for a given workspace, namespace and name.
func (s *compiledShardNamespaceLister) Get(name string) (*deployv1alpha1.CompiledShard, error) {
	key := kcpcache.ToClusterAwareKey(s.clusterName.String(), s.namespace, name)
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(deployv1alpha1.Resource("compiledshards"), name)
	}
	return obj.(*deployv1alpha1.CompiledShard), nil
}

// NewCompiledShardLister returns a new CompiledShardLister.
// We assume that the indexer:
// - is fed by a workspace-scoped LIST+WATCH
// - uses cache.MetaNamespaceKeyFunc as the key function
// - has the cache.NamespaceIndex as an index
func NewCompiledShardLister(indexer cache.Indexer) *compiledShardScopedLister {
	return &compiledShardScopedLister{indexer: indexer}
}

// compiledShardScopedLister can list all CompiledShards inside a workspace or scope down to a CompiledShardLister for one namespace.
type compiledShardScopedLister struct {
	indexer cache.Indexer
}

// List lists all CompiledShards in the indexer for a workspace.
func (s *compiledShardScopedLister) List(selector labels.Selector) (ret []*deployv1alpha1.CompiledShard, err error) {
	err = cache.ListAll(s.indexer, selector, func(i interface{}) {
		ret = append(ret, i.(*deployv1alpha1.CompiledShard))
	})
	return ret, err
}

// CompiledShards returns an object that can list and get CompiledShards in one namespace.
func (s *compiledShardScopedLister) CompiledShards(namespace string) CompiledShardNamespaceLister {
	return &compiledShardScopedNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// compiledShardScopedNamespaceLister helps list and get CompiledShards.
type compiledShardScopedNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all CompiledShards in the indexer for a given workspace and namespace.
func (s *compiledShardScopedNamespaceLister) List(selector labels.Selector) (ret []*deployv1alpha1.CompiledShard, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(i interface{}) {
		ret = append(ret, i.(*deployv1alpha1.CompiledShard))
	})
	return ret, err
}

// Get retrieves the CompiledShard from the indexer for a given workspace, namespace and name.
func (s *compiledShardScopedNamespaceLister) Get(name string) (*deployv1alpha1.CompiledShard, error) {
	key := s.namespace + "/" + name
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(deployv1alpha1.Resource("compiledshards"), name)
	}
	return obj.(*deployv1alpha1.CompiledShard), nil
}
