//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024 The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	kcpcache "github.com/kcp-dev/apimachinery/v2/pkg/cache"
	"github.com/kcp-dev/logicalcluster/v3"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"

	deployv1alpha1 "github.com/kcp-dev/kcp-operator/sdk/apis/deploy/v1alpha1"
)

// CompiledCacheServerClusterLister can list CompiledCacheServers across all workspaces, or scope down to a CompiledCacheServerLister for one workspace.
// All objects returned here must be treated as read-only.
type CompiledCacheServerClusterLister interface {
	// List lists all CompiledCacheServers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*deployv1alpha1.CompiledCacheServer, err error)
	// Cluster returns a lister that can list and get CompiledCacheServers in one workspace.
	Cluster(clusterName logicalcluster.Name) CompiledCacheServerLister
	CompiledCacheServerClusterListerExpansion
}

type compiledCacheServerClusterLister struct {
	indexer cache.Indexer
}

// NewCompiledCacheServerClusterLister returns a new CompiledCacheServerClusterLister.
// We assume that the indexer:
// - is fed by a cross-workspace LIST+WATCH
// - uses kcpcache.MetaClusterNamespaceKeyFunc as the key function
// - has the kcpcache.ClusterIndex as an index
// - has the kcpcache.ClusterAndNamespaceIndex as an index
func NewCompiledCacheServerClusterLister(indexer cache.Indexer) *compiledCacheServerClusterLister {
	return &compiledCacheServerClusterLister{indexer: indexer}
}

// List lists all CompiledCacheServers in the indexer across all workspaces.
func (s *compiledCacheServerClusterLister) List(selector labels.Selector) (ret []*deployv1alpha1.CompiledCacheServer, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*deployv1alpha1.CompiledCacheServer))
	})
	return ret, err
}

// Cluster scopes the lister to one workspace, allowing users to list and get CompiledCacheServers.
func (s *compiledCacheServerClusterLister) Cluster(clusterName logicalcluster.Name) CompiledCacheServerLister {
	return &compiledCacheServerLister{indexer: s.indexer, clusterName: clusterName}
}

// CompiledCacheServerLister can list CompiledCacheServers across all namespaces, or scope down to a CompiledCacheServerNamespaceLister for one namespace.
// All objects returned here must be treated as read-only.
type CompiledCacheServerLister interface {
	// List lists all CompiledCacheServers in the workspace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*deployv1alpha1.CompiledCacheServer, err error)
	// CompiledCacheServers returns a lister that can list and get CompiledCacheServers in one workspace and namespace.
	CompiledCacheServers(namespace string) CompiledCacheServerNamespaceLister
	CompiledCacheServerListerExpansion
}

// compiledCacheServerLister can list all CompiledCacheServers inside a workspace or scope down to a CompiledCacheServerLister for one namespace.
type compiledCacheServerLister struct {
	indexer     cache.Indexer
	clusterName logicalcluster.Name
}

// List lists all CompiledCacheServers in the indexer for a workspace.
func (s *compiledCacheServerLister) List(selector labels.Selector) (ret []*deployv1alpha1.CompiledCacheServer, err error) {
	err = kcpcache.ListAllByCluster(s.indexer, s.clusterName, selector, func(i interface{}) {
		ret = append(ret, i.(*deployv1alpha1.CompiledCacheServer))
	})
	return ret, err
}

// CompiledCacheServers returns an object that can list and get CompiledCacheServers in one namespace.
func (s *compiledCacheServerLister) CompiledCacheServers(namespace string) CompiledCacheServerNamespaceLister {
	return &compiledCacheServerNamespaceLister{indexer: s.indexer, clusterName: s.clusterName, namespace: namespace}
}

// compiledCacheServerNamespaceLister helps list and get CompiledCacheServers.
// All objects returned here must be treated as read-only.
type CompiledCacheServerNamespaceLister interface {
	// List lists all CompiledCacheServers in the workspace and namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*deployv1alpha1.CompiledCacheServer, err error)
	// Get retrieves the CompiledCacheServer from the indexer for a given workspace, namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*deployv1alpha1.CompiledCacheServer, error)
	CompiledCacheServerNamespaceListerExpansion
}

// compiledCacheServerNamespaceLister helps list and get CompiledCacheServers.
// All objects returned here must be treated as read-only.
type compiledCacheServerNamespaceLister struct {
	indexer     cache.Indexer
	clusterName logicalcluster.Name
	namespace   string
}

// List lists all CompiledCacheServers in the indexer for a given workspace and namespace.
func (s *compiledCacheServerNamespaceLister) List(selector labels.Selector) (ret []*deployv1alpha1.CompiledCacheServer, err error) {
	err = kcpcache.ListAllByClusterAndNamespace(s.indexer, s.clusterName, s.namespace, selector, func(i interface{}) {
		ret = append(ret, i.(*deployv1alpha1.CompiledCacheServer))
	})
	return ret, err
}

// Get retrieves the CompiledCacheServer from the indexer for a given workspace, namespace and name.
func (s *compiledCacheServerNamespaceLister) Get(name string) (*deployv1alpha1.CompiledCacheServer, error) {
	key := kcpcache.ToClusterAwareKey(s.clusterName.String(), s.namespace, name)
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(deployv1alpha1.Resource("compiledcacheservers"), name)
	}
	return obj.(*deployv1alpha1.CompiledCacheServer), nil
}

// NewCompiledCacheServerLister returns a new CompiledCacheServerLister.
// We assume that the indexer:
// - is fed by a workspace-scoped LIST+WATCH
// - uses cache.MetaNamespaceKeyFunc as the key function
// - has the cache.NamespaceIndex as an index
func NewCompiledCacheServerLister(indexer cache.Indexer) *compiledCacheServerScopedLister {
	return &compiledCacheServerScopedLister{indexer: indexer}
}

// compiledCacheServerScopedLister can list all CompiledCacheServers inside a workspace or scope down to a CompiledCacheServerLister for one namespace.
type compiledCacheServerScopedLister struct {
	indexer cache.Indexer
}

// List lists all CompiledCacheServers in the indexer for a workspace.
func (s *compiledCacheServerScopedLister) List(selector labels.Selector) (ret []*deployv1alpha1.CompiledCacheServer, err error) {
	err = cache.ListAll(s.indexer, selector, func(i interface{}) {
		ret = append(ret, i.(*deployv1alpha1.CompiledCacheServer))
	})
	return ret, err
}

// CompiledCacheServers returns an object that can list and get CompiledCacheServers in one namespace.
func (s *compiledCacheServerScopedLister) CompiledCacheServers(namespace string) CompiledCacheServerNamespaceLister {
	return &compiledCacheServerScopedNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// compiledCacheServerScopedNamespaceLister helps list and get CompiledCacheServers.
type compiledCacheServerScopedNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all CompiledCacheServers in the indexer for a given workspace and namespace.
func (s *compiledCacheServerScopedNamespaceLister) List(selector labels.Selector) (ret []*deployv1alpha1.CompiledCacheServer, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(i interface{}) {
		ret = append(ret, i.(*deployv1alpha1.CompiledCacheServer))
	})
	return ret, err
}

// Get retrieves the CompiledCacheServer from the indexer for a given workspace, namespace and name.
func (s *compiledCacheServerScopedNamespaceLister) Get(name string) (*deployv1alpha1.CompiledCacheServer, error) {
	key := s.namespace + "/" + name
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(deployv1alpha1.Resource("compiledcacheservers"), name)
	}
	return obj.(*deployv1alpha1.CompiledCacheServer), nil
}
