//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024 The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	kcpcache "github.com/kcp-dev/apimachinery/v2/pkg/cache"
	"github.com/kcp-dev/logicalcluster/v3"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"

	deployv1alpha1 "github.com/kcp-dev/kcp-operator/sdk/apis/deploy/v1alpha1"
)

// CompiledVirtualWorkspaceClusterLister can list CompiledVirtualWorkspaces across all workspaces, or scope down to a CompiledVirtualWorkspaceLister for one workspace.
// All objects returned here must be treated as read-only.
type CompiledVirtualWorkspaceClusterLister interface {
	// List lists all CompiledVirtualWorkspaces in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*deployv1alpha1.CompiledVirtualWorkspace, err error)
	// Cluster returns a lister that can list and get CompiledVirtualWorkspaces in one workspace.
	Cluster(clusterName logicalcluster.Name) CompiledVirtualWorkspaceLister
	CompiledVirtualWorkspaceClusterListerExpansion
}

type compiledVirtualWorkspaceClusterLister struct {
	indexer cache.Indexer
}

// NewCompiledVirtualWorkspaceClusterLister returns a new CompiledVirtualWorkspaceClusterLister.
// We assume that the indexer:
// - is fed by a cross-workspace LIST+WATCH
// - uses kcpcache.MetaClusterNamespaceKeyFunc as the key function
// - has the kcpcache.ClusterIndex as an index
// - has the kcpcache.ClusterAndNamespaceIndex as an index
func NewCompiledVirtualWorkspaceClusterLister(indexer cache.Indexer) *compiledVirtualWorkspaceClusterLister {
	return &compiledVirtualWorkspaceClusterLister{indexer: indexer}
}

// List lists all CompiledVirtualWorkspaces in the indexer across all workspaces.
func (s *compiledVirtualWorkspaceClusterLister) List(selector labels.Selector) (ret []*deployv1alpha1.CompiledVirtualWorkspace, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*deployv1alpha1.CompiledVirtualWorkspace))
	})
	return ret, err
}

// Cluster scopes the lister to one workspace, allowing users to list and get CompiledVirtualWorkspaces.
func (s *compiledVirtualWorkspaceClusterLister) Cluster(clusterName logicalcluster.Name) CompiledVirtualWorkspaceLister {
	return &compiledVirtualWorkspaceLister{indexer: s.indexer, clusterName: clusterName}
}

// CompiledVirtualWorkspaceLister can list CompiledVirtualWorkspaces across all namespaces, or scope down to a CompiledVirtualWorkspaceNamespaceLister for one namespace.
// All objects returned here must be treated as read-only.
type CompiledVirtualWorkspaceLister interface {
	// List lists all CompiledVirtualWorkspaces in the workspace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*deployv1alpha1.CompiledVirtualWorkspace, err error)
	// CompiledVirtualWorkspaces returns a lister that can list and get CompiledVirtualWorkspaces in one workspace and namespace.
	CompiledVirtualWorkspaces(namespace string) CompiledVirtualWorkspaceNamespaceLister
	CompiledVirtualWorkspaceListerExpansion
}

// compiledVirtualWorkspaceLister can list all CompiledVirtualWorkspaces inside a workspace or scope down to a CompiledVirtualWorkspaceLister for one namespace.
type compiledVirtualWorkspaceLister struct {
	indexer     cache.Indexer
	clusterName logicalcluster.Name
}

// List lists all CompiledVirtualWorkspaces in the indexer for a workspace.
func (s *compiledVirtualWorkspaceLister) List(selector labels.Selector) (ret []*deployv1alpha1.CompiledVirtualWorkspace, err error) {
	err = kcpcache.ListAllByCluster(s.indexer, s.clusterName, selector, func(i interface{}) {
		ret = append(ret, i.(*deployv1alpha1.CompiledVirtualWorkspace))
	})
	return ret, err
}

// CompiledVirtualWorkspaces returns an object that can list and get CompiledVirtualWorkspaces in one namespace.
func (s *compiledVirtualWorkspaceLister) CompiledVirtualWorkspaces(namespace string) CompiledVirtualWorkspaceNamespaceLister {
	return &compiledVirtualWorkspaceNamespaceLister{indexer: s.indexer, clusterName: s.clusterName, namespace: namespace}
}

// compiledVirtualWorkspaceNamespaceLister helps list and get CompiledVirtualWorkspaces.
// All objects returned here must be treated as read-only.
type CompiledVirtualWorkspaceNamespaceLister interface {
	// List lists all CompiledVirtualWorkspaces in the workspace and namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*deployv1alpha1.CompiledVirtualWorkspace, err error)
	// Get retrieves the CompiledVirtualWorkspace from the indexer for a given workspace, namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*deployv1alpha1.CompiledVirtualWorkspace, error)
	CompiledVirtualWorkspaceNamespaceListerExpansion
}

// compiledVirtualWorkspaceNamespaceLister helps list and get CompiledVirtualWorkspaces.
// All objects returned here must be treated as read-only.
type compiledVirtualWorkspaceNamespaceLister struct {
	indexer     cache.Indexer
	clusterName logicalcluster.Name
	namespace   string
}

// List lists all CompiledVirtualWorkspaces in the indexer for a given workspace and namespace.
func (s *compiledVirtualWorkspaceNamespaceLister) List(selector labels.Selector) (ret []*deployv1alpha1.CompiledVirtualWorkspace, err error) {
	err = kcpcache.ListAllByClusterAndNamespace(s.indexer, s.clusterName, s.namespace, selector, func(i interface{}) {
		ret = append(ret, i.(*deployv1alpha1.CompiledVirtualWorkspace))
	})
	return ret, err
}

// Get retrieves the CompiledVirtualWorkspace from the indexer for a given workspace, namespace and name.
func (s *compiledVirtualWorkspaceNamespaceLister) Get(name string) (*deployv1alpha1.CompiledVirtualWorkspace, error) {
	key := kcpcache.ToClusterAwareKey(s.clusterName.String(), s.namespace, name)
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(deployv1alpha1.Resource("compiledvirtualworkspaces"), name)
	}
	return obj.(*deployv1alpha1.CompiledVirtualWorkspace), nil
}

// NewCompiledVirtualWorkspaceLister returns a new CompiledVirtualWorkspaceLister.
// We assume that the indexer:
// - is fed by a workspace-scoped LIST+WATCH
// - uses cache.MetaNamespaceKeyFunc as the key function
// - has the cache.NamespaceIndex as an index
func NewCompiledVirtualWorkspaceLister(indexer cache.Indexer) *compiledVirtualWorkspaceScopedLister {
	return &compiledVirtualWorkspaceScopedLister{indexer: indexer}
}

// compiledVirtualWorkspaceScopedLister can list all CompiledVirtualWorkspaces inside a workspace or scope down to a CompiledVirtualWorkspaceLister for one namespace.
type compiledVirtualWorkspaceScopedLister struct {
	indexer cache.Indexer
}

// List lists all CompiledVirtualWorkspaces in the indexer for a workspace.
func (s *compiledVirtualWorkspaceScopedLister) List(selector labels.Selector) (ret []*deployv1alpha1.CompiledVirtualWorkspace, err error) {
	err = cache.ListAll(s.indexer, selector, func(i interface{}) {
		ret = append(ret, i.(*deployv1alpha1.CompiledVirtualWorkspace))
	})
	return ret, err
}

// CompiledVirtualWorkspaces returns an object that can list and get CompiledVirtualWorkspaces in one namespace.
func (s *compiledVirtualWorkspaceScopedLister) CompiledVirtualWorkspaces(namespace string) CompiledVirtualWorkspaceNamespaceLister {
	return &compiledVirtualWorkspaceScopedNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// compiledVirtualWorkspaceScopedNamespaceLister helps list and get CompiledVirtualWorkspaces.
type compiledVirtualWorkspaceScopedNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all CompiledVirtualWorkspaces in the indexer for a given workspace and namespace.
func (s *compiledVirtualWorkspaceScopedNamespaceLister) List(selector labels.Selector) (ret []*deployv1alpha1.CompiledVirtualWorkspace, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(i interface{}) {
		ret = append(ret, i.(*deployv1alpha1.CompiledVirtualWorkspace))
	})
	return ret, err
}

// Get retrieves the CompiledVirtualWorkspace from the indexer for a given workspace, namespace and name.
func (s *compiledVirtualWorkspaceScopedNamespaceLister) Get(name string) (*deployv1alpha1.CompiledVirtualWorkspace, error) {
	key := s.namespace + "/" + name
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(deployv1alpha1.Resource("compiledvirtualworkspaces"), name)
	}
	return obj.(*deployv1alpha1.CompiledVirtualWorkspace), nil
}
