//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024 The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	kcpcache "github.com/kcp-dev/apimachinery/v2/pkg/cache"
	"github.com/kcp-dev/logicalcluster/v3"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"

	deployv1alpha1 "github.com/kcp-dev/kcp-operator/sdk/apis/deploy/v1alpha1"
)

// CompiledFrontProxyClusterLister can list CompiledFrontProxies across all workspaces, or scope down to a CompiledFrontProxyLister for one workspace.
// All objects returned here must be treated as read-only.
type CompiledFrontProxyClusterLister interface {
	// List lists all CompiledFrontProxies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*deployv1alpha1.CompiledFrontProxy, err error)
	// Cluster returns a lister that can list and get CompiledFrontProxies in one workspace.
	Cluster(clusterName logicalcluster.Name) CompiledFrontProxyLister
	CompiledFrontProxyClusterListerExpansion
}

type compiledFrontProxyClusterLister struct {
	indexer cache.Indexer
}

// NewCompiledFrontProxyClusterLister returns a new CompiledFrontProxyClusterLister.
// We assume that the indexer:
// - is fed by a cross-workspace LIST+WATCH
// - uses kcpcache.MetaClusterNamespaceKeyFunc as the key function
// - has the kcpcache.ClusterIndex as an index
// - has the kcpcache.ClusterAndNamespaceIndex as an index
func NewCompiledFrontProxyClusterLister(indexer cache.Indexer) *compiledFrontProxyClusterLister {
	return &compiledFrontProxyClusterLister{indexer: indexer}
}

// List lists all CompiledFrontProxies in the indexer across all workspaces.
func (s *compiledFrontProxyClusterLister) List(selector labels.Selector) (ret []*deployv1alpha1.CompiledFrontProxy, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*deployv1alpha1.CompiledFrontProxy))
	})
	return ret, err
}

// Cluster scopes the lister to one workspace, allowing users to list and get CompiledFrontProxies.
func (s *compiledFrontProxyClusterLister) Cluster(clusterName logicalcluster.Name) CompiledFrontProxyLister {
	return &compiledFrontProxyLister{indexer: s.indexer, clusterName: clusterName}
}

// CompiledFrontProxyLister can list CompiledFrontProxies across all namespaces, or scope down to a CompiledFrontProxyNamespaceLister for one namespace.
// All objects returned here must be treated as read-only.
type CompiledFrontProxyLister interface {
	// List lists all CompiledFrontProxies in the workspace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*deployv1alpha1.CompiledFrontProxy, err error)
	// CompiledFrontProxies returns a lister that can list and get CompiledFrontProxies in one workspace and namespace.
	CompiledFrontProxies(namespace string) CompiledFrontProxyNamespaceLister
	CompiledFrontProxyListerExpansion
}

// compiledFrontProxyLister can list all CompiledFrontProxies inside a workspace or scope down to a CompiledFrontProxyLister for one namespace.
type compiledFrontProxyLister struct {
	indexer     cache.Indexer
	clusterName logicalcluster.Name
}

// List lists all CompiledFrontProxies in the indexer for a workspace.
func (s *compiledFrontProxyLister) List(selector labels.Selector) (ret []*deployv1alpha1.CompiledFrontProxy, err error) {
	err = kcpcache.ListAllByCluster(s.indexer, s.clusterName, selector, func(i interface{}) {
		ret = append(ret, i.(*deployv1alpha1.CompiledFrontProxy))
	})
	return ret, err
}

// CompiledFrontProxies returns an object that can list and get CompiledFrontProxies in one namespace.
func (s *compiledFrontProxyLister) CompiledFrontProxies(namespace string) CompiledFrontProxyNamespaceLister {
	return &compiledFrontProxyNamespaceLister{indexer: s.indexer, clusterName: s.clusterName, namespace: namespace}
}

// compiledFrontProxyNamespaceLister helps list and get CompiledFrontProxies.
// All objects returned here must be treated as read-only.
type CompiledFrontProxyNamespaceLister interface {
	// List lists all CompiledFrontProxies in the workspace and namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*deployv1alpha1.CompiledFrontProxy, err error)
	// Get retrieves the CompiledFrontProxy from the indexer for a given workspace, namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*deployv1alpha1.CompiledFrontProxy, error)
	CompiledFrontProxyNamespaceListerExpansion
}

// compiledFrontProxyNamespaceLister helps list and get CompiledFrontProxies.
// All objects returned here must be treated as read-only.
type compiledFrontProxyNamespaceLister struct {
	indexer     cache.Indexer
	clusterName logicalcluster.Name
	namespace   string
}

// List lists all CompiledFrontProxies in the indexer for a given workspace and namespace.
func (s *compiledFrontProxyNamespaceLister) List(selector labels.Selector) (ret []*deployv1alpha1.CompiledFrontProxy, err error) {
	err = kcpcache.ListAllByClusterAndNamespace(s.indexer, s.clusterName, s.namespace, selector, func(i interface{}) {
		ret = append(ret, i.(*deployv1alpha1.CompiledFrontProxy))
	})
	return ret, err
}

// Get retrieves the CompiledFrontProxy from the indexer for a given workspace, namespace and name.
func (s *compiledFrontProxyNamespaceLister) Get(name string) (*deployv1alpha1.CompiledFrontProxy, error) {
	key := kcpcache.ToClusterAwareKey(s.clusterName.String(), s.namespace, name)
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(deployv1alpha1.Resource("compiledfrontproxies"), name)
	}
	return obj.(*deployv1alpha1.CompiledFrontProxy), nil
}

// NewCompiledFrontProxyLister returns a new CompiledFrontProxyLister.
// We assume that the indexer:
// - is fed by a workspace-scoped LIST+WATCH
// - uses cache.MetaNamespaceKeyFunc as the key function
// - has the cache.NamespaceIndex as an index
func NewCompiledFrontProxyLister(indexer cache.Indexer) *compiledFrontProxyScopedLister {
	return &compiledFrontProxyScopedLister{indexer: indexer}
}

// compiledFrontProxyScopedLister can list all CompiledFrontProxies inside a workspace or scope down to a CompiledFrontProxyLister for one namespace.
type compiledFrontProxyScopedLister struct {
	indexer cache.Indexer
}

// List lists all CompiledFrontProxies in the indexer for a workspace.
func (s *compiledFrontProxyScopedLister) List(selector labels.Selector) (ret []*deployv1alpha1.CompiledFrontProxy, err error) {
	err = cache.ListAll(s.indexer, selector, func(i interface{}) {
		ret = append(ret, i.(*deployv1alpha1.CompiledFrontProxy))
	})
	return ret, err
}

// CompiledFrontProxies returns an object that can list and get CompiledFrontProxies in one namespace.
func (s *compiledFrontProxyScopedLister) CompiledFrontProxies(namespace string) CompiledFrontProxyNamespaceLister {
	return &compiledFrontProxyScopedNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// compiledFrontProxyScopedNamespaceLister helps list and get CompiledFrontProxies.
type compiledFrontProxyScopedNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all CompiledFrontProxies in the indexer for a given workspace and namespace.
func (s *compiledFrontProxyScopedNamespaceLister) List(selector labels.Selector) (ret []*deployv1alpha1.CompiledFrontProxy, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(i interface{}) {
		ret = append(ret, i.(*deployv1alpha1.CompiledFrontProxy))
	})
	return ret, err
}

// Get retrieves the CompiledFrontProxy from the indexer for a given workspace, namespace and name.
func (s *compiledFrontProxyScopedNamespaceLister) Get(name string) (*deployv1alpha1.CompiledFrontProxy, error) {
	key := s.namespace + "/" + name
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(deployv1alpha1.Resource("compiledfrontproxies"), name)
	}
	return obj.(*deployv1alpha1.CompiledFrontProxy), nil
}
