//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024 The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	kcpcache "github.com/kcp-dev/apimachinery/v2/pkg/cache"
	"github.com/kcp-dev/logicalcluster/v3"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"

	deployv1alpha1 "github.com/kcp-dev/kcp-operator/sdk/apis/deploy/v1alpha1"
)

// CompiledRootShardClusterLister can list CompiledRootShards across all workspaces, or scope down to a CompiledRootShardLister for one workspace.
// All objects returned here must be treated as read-only.
type CompiledRootShardClusterLister interface {
	// List lists all CompiledRootShards in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*deployv1alpha1.CompiledRootShard, err error)
	// Cluster returns a lister that can list and get CompiledRootShards in one workspace.
	Cluster(clusterName logicalcluster.Name) CompiledRootShardLister
	CompiledRootShardClusterListerExpansion
}

type compiledRootShardClusterLister struct {
	indexer cache.Indexer
}

// NewCompiledRootShardClusterLister returns a new CompiledRootShardClusterLister.
// We assume that the indexer:
// - is fed by a cross-workspace LIST+WATCH
// - uses kcpcache.MetaClusterNamespaceKeyFunc as the key function
// - has the kcpcache.ClusterIndex as an index
// - has the kcpcache.ClusterAndNamespaceIndex as an index
func NewCompiledRootShardClusterLister(indexer cache.Indexer) *compiledRootShardClusterLister {
	return &compiledRootShardClusterLister{indexer: indexer}
}

// List lists all CompiledRootShards in the indexer across all workspaces.
func (s *compiledRootShardClusterLister) List(selector labels.Selector) (ret []*deployv1alpha1.CompiledRootShard, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*deployv1alpha1.CompiledRootShard))
	})
	return ret, err
}

// Cluster scopes the lister to one workspace, allowing users to list and get CompiledRootShards.
func (s *compiledRootShardClusterLister) Cluster(clusterName logicalcluster.Name) CompiledRootShardLister {
	return &compiledRootShardLister{indexer: s.indexer, clusterName: clusterName}
}

// CompiledRootShardLister can list CompiledRootShards across all namespaces, or scope down to a CompiledRootShardNamespaceLister for one namespace.
// All objects returned here must be treated as read-only.
type CompiledRootShardLister interface {
	// List lists all CompiledRootShards in the workspace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*deployv1alpha1.CompiledRootShard, err error)
	// CompiledRootShards returns a lister that can list and get CompiledRootShards in one workspace and namespace.
	CompiledRootShards(namespace string) CompiledRootShardNamespaceLister
	CompiledRootShardListerExpansion
}

// compiledRootShardLister can list all CompiledRootShards inside a workspace or scope down to a CompiledRootShardLister for one namespace.
type compiledRootShardLister struct {
	indexer     cache.Indexer
	clusterName logicalcluster.Name
}

// List lists all CompiledRootShards in the indexer for a workspace.
func (s *compiledRootShardLister) List(selector labels.Selector) (ret []*deployv1alpha1.CompiledRootShard, err error) {
	err = kcpcache.ListAllByCluster(s.indexer, s.clusterName, selector, func(i interface{}) {
		ret = append(ret, i.(*deployv1alpha1.CompiledRootShard))
	})
	return ret, err
}

// CompiledRootShards returns an object that can list and get CompiledRootShards in one namespace.
func (s *compiledRootShardLister) CompiledRootShards(namespace string) CompiledRootShardNamespaceLister {
	return &compiledRootShardNamespaceLister{indexer: s.indexer, clusterName: s.clusterName, namespace: namespace}
}

// compiledRootShardNamespaceLister helps list and get CompiledRootShards.
// All objects returned here must be treated as read-only.
type CompiledRootShardNamespaceLister interface {
	// List lists all CompiledRootShards in the workspace and namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*deployv1alpha1.CompiledRootShard, err error)
	// Get retrieves the CompiledRootShard from the indexer for a given workspace, namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*deployv1alpha1.CompiledRootShard, error)
	CompiledRootShardNamespaceListerExpansion
}

// compiledRootShardNamespaceLister helps list and get CompiledRootShards.
// All objects returned here must be treated as read-only.
type compiledRootShardNamespaceLister struct {
	indexer     cache.Indexer
	clusterName logicalcluster.Name
	namespace   string
}

// List lists all CompiledRootShards in the indexer for a given workspace and namespace.
func (s *compiledRootShardNamespaceLister) List(selector labels.Selector) (ret []*deployv1alpha1.CompiledRootShard, err error) {
	err = kcpcache.ListAllByClusterAndNamespace(s.indexer, s.clusterName, s.namespace, selector, func(i interface{}) {
		ret = append(ret, i.(*deployv1alpha1.CompiledRootShard))
	})
	return ret, err
}

// Get retrieves the CompiledRootShard from the indexer for a given workspace, namespace and name.
func (s *compiledRootShardNamespaceLister) Get(name string) (*deployv1alpha1.CompiledRootShard, error) {
	key := kcpcache.ToClusterAwareKey(s.clusterName.String(), s.namespace, name)
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(deployv1alpha1.Resource("compiledrootshards"), name)
	}
	return obj.(*deployv1alpha1.CompiledRootShard), nil
}

// NewCompiledRootShardLister returns a new CompiledRootShardLister.
// We assume that the indexer:
// - is fed by a workspace-scoped LIST+WATCH
// - uses cache.MetaNamespaceKeyFunc as the key function
// - has the cache.NamespaceIndex as an index
func NewCompiledRootShardLister(indexer cache.Indexer) *compiledRootShardScopedLister {
	return &compiledRootShardScopedLister{indexer: indexer}
}

// compiledRootShardScopedLister can list all CompiledRootShards inside a workspace or scope down to a CompiledRootShardLister for one namespace.
type compiledRootShardScopedLister struct {
	indexer cache.Indexer
}

// List lists all CompiledRootShards in the indexer for a workspace.
func (s *compiledRootShardScopedLister) List(selector labels.Selector) (ret []*deployv1alpha1.CompiledRootShard, err error) {
	err = cache.ListAll(s.indexer, selector, func(i interface{}) {
		ret = append(ret, i.(*deployv1alpha1.CompiledRootShard))
	})
	return ret, err
}

// CompiledRootShards returns an object that can list and get CompiledRootShards in one namespace.
func (s *compiledRootShardScopedLister) CompiledRootShards(namespace string) CompiledRootShardNamespaceLister {
	return &compiledRootShardScopedNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// compiledRootShardScopedNamespaceLister helps list and get CompiledRootShards.
type compiledRootShardScopedNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all CompiledRootShards in the indexer for a given workspace and namespace.
func (s *compiledRootShardScopedNamespaceLister) List(selector labels.Selector) (ret []*deployv1alpha1.CompiledRootShard, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(i interface{}) {
		ret = append(ret, i.(*deployv1alpha1.CompiledRootShard))
	})
	return ret, err
}

// Get retrieves the CompiledRootShard from the indexer for a given workspace, namespace and name.
func (s *compiledRootShardScopedNamespaceLister) Get(name string) (*deployv1alpha1.CompiledRootShard, error) {
	key := s.namespace + "/" + name
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(deployv1alpha1.Resource("compiledrootshards"), name)
	}
	return obj.(*deployv1alpha1.CompiledRootShard), nil
}
