//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024 The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	"context"

	kcpclient "github.com/kcp-dev/apimachinery/v2/pkg/client"
	"github.com/kcp-dev/logicalcluster/v3"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/watch"

	deployv1alpha1 "github.com/kcp-dev/kcp-operator/sdk/apis/deploy/v1alpha1"
	deployv1alpha1client "github.com/kcp-dev/kcp-operator/sdk/clientset/versioned/typed/deploy/v1alpha1"
)

// CompiledVirtualWorkspacesClusterGetter has a method to return a CompiledVirtualWorkspaceClusterInterface.
// A group's cluster client should implement this interface.
type CompiledVirtualWorkspacesClusterGetter interface {
	CompiledVirtualWorkspaces() CompiledVirtualWorkspaceClusterInterface
}

// CompiledVirtualWorkspaceClusterInterface can operate on CompiledVirtualWorkspaces across all clusters,
// or scope down to one cluster and return a CompiledVirtualWorkspacesNamespacer.
type CompiledVirtualWorkspaceClusterInterface interface {
	Cluster(logicalcluster.Path) CompiledVirtualWorkspacesNamespacer
	List(ctx context.Context, opts metav1.ListOptions) (*deployv1alpha1.CompiledVirtualWorkspaceList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
}

type compiledVirtualWorkspacesClusterInterface struct {
	clientCache kcpclient.Cache[*deployv1alpha1client.DeployV1alpha1Client]
}

// Cluster scopes the client down to a particular cluster.
func (c *compiledVirtualWorkspacesClusterInterface) Cluster(clusterPath logicalcluster.Path) CompiledVirtualWorkspacesNamespacer {
	if clusterPath == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}

	return &compiledVirtualWorkspacesNamespacer{clientCache: c.clientCache, clusterPath: clusterPath}
}

// List returns the entire collection of all CompiledVirtualWorkspaces across all clusters.
func (c *compiledVirtualWorkspacesClusterInterface) List(ctx context.Context, opts metav1.ListOptions) (*deployv1alpha1.CompiledVirtualWorkspaceList, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).CompiledVirtualWorkspaces(metav1.NamespaceAll).List(ctx, opts)
}

// Watch begins to watch all CompiledVirtualWorkspaces across all clusters.
func (c *compiledVirtualWorkspacesClusterInterface) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).CompiledVirtualWorkspaces(metav1.NamespaceAll).Watch(ctx, opts)
}

// CompiledVirtualWorkspacesNamespacer can scope to objects within a namespace, returning a deployv1alpha1client.CompiledVirtualWorkspaceInterface.
type CompiledVirtualWorkspacesNamespacer interface {
	Namespace(string) deployv1alpha1client.CompiledVirtualWorkspaceInterface
}

type compiledVirtualWorkspacesNamespacer struct {
	clientCache kcpclient.Cache[*deployv1alpha1client.DeployV1alpha1Client]
	clusterPath logicalcluster.Path
}

func (n *compiledVirtualWorkspacesNamespacer) Namespace(namespace string) deployv1alpha1client.CompiledVirtualWorkspaceInterface {
	return n.clientCache.ClusterOrDie(n.clusterPath).CompiledVirtualWorkspaces(namespace)
}
