//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024 The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	"context"

	kcpclient "github.com/kcp-dev/apimachinery/v2/pkg/client"
	"github.com/kcp-dev/logicalcluster/v3"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/watch"

	deployv1alpha1 "github.com/kcp-dev/kcp-operator/sdk/apis/deploy/v1alpha1"
	deployv1alpha1client "github.com/kcp-dev/kcp-operator/sdk/clientset/versioned/typed/deploy/v1alpha1"
)

// CompiledShardsClusterGetter has a method to return a CompiledShardClusterInterface.
// A group's cluster client should implement this interface.
type CompiledShardsClusterGetter interface {
	CompiledShards() CompiledShardClusterInterface
}

// CompiledShardClusterInterface can operate on CompiledShards across all clusters,
// or scope down to one cluster and return a CompiledShardsNamespacer.
type CompiledShardClusterInterface interface {
	Cluster(logicalcluster.Path) CompiledShardsNamespacer
	List(ctx context.Context, opts metav1.ListOptions) (*deployv1alpha1.CompiledShardList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
}

type compiledShardsClusterInterface struct {
	clientCache kcpclient.Cache[*deployv1alpha1client.DeployV1alpha1Client]
}

// Cluster scopes the client down to a particular cluster.
func (c *compiledShardsClusterInterface) Cluster(clusterPath logicalcluster.Path) CompiledShardsNamespacer {
	if clusterPath == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}

	return &compiledShardsNamespacer{clientCache: c.clientCache, clusterPath: clusterPath}
}

// List returns the entire collection of all CompiledShards across all clusters.
func (c *compiledShardsClusterInterface) List(ctx context.Context, opts metav1.ListOptions) (*deployv1alpha1.CompiledShardList, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).CompiledShards(metav1.NamespaceAll).List(ctx, opts)
}

// Watch begins to watch all CompiledShards across all clusters.
func (c *compiledShardsClusterInterface) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).CompiledShards(metav1.NamespaceAll).Watch(ctx, opts)
}

// CompiledShardsNamespacer can scope to objects within a namespace, returning a deployv1alpha1client.CompiledShardInterface.
type CompiledShardsNamespacer interface {
	Namespace(string) deployv1alpha1client.CompiledShardInterface
}

type compiledShardsNamespacer struct {
	clientCache kcpclient.Cache[*deployv1alpha1client.DeployV1alpha1Client]
	clusterPath logicalcluster.Path
}

func (n *compiledShardsNamespacer) Namespace(namespace string) deployv1alpha1client.CompiledShardInterface {
	return n.clientCache.ClusterOrDie(n.clusterPath).CompiledShards(namespace)
}
