/*
Copyright 2024 The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen-v0.32. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"

	operatorv1alpha1 "github.com/kcp-dev/kcp-operator/sdk/apis/operator/v1alpha1"
)

// CacheServerSpecApplyConfiguration represents a declarative configuration of the CacheServerSpec type for use
// with apply.
type CacheServerSpecApplyConfiguration struct {
	ClusterDomain        *string                                  `json:"clusterDomain,omitempty"`
	Image                *ImageSpecApplyConfiguration             `json:"image,omitempty"`
	Replicas             *int32                                   `json:"replicas,omitempty"`
	Logging              *LoggingSpecApplyConfiguration           `json:"logging,omitempty"`
	Certificates         *CertificatesApplyConfiguration          `json:"certificates,omitempty"`
	CertificateTemplates *operatorv1alpha1.CertificateTemplateMap `json:"certificateTemplates,omitempty"`
	ServiceTemplate      *ServiceTemplateApplyConfiguration       `json:"serviceTemplate,omitempty"`
	DeploymentTemplate   *DeploymentTemplateApplyConfiguration    `json:"deploymentTemplate,omitempty"`
	Etcd                 *EtcdConfigApplyConfiguration            `json:"etcd,omitempty"`
	ExtraArgs            []string                                 `json:"extraArgs,omitempty"`
	ExtraVolumes         []v1.Volume                              `json:"extraVolumes,omitempty"`
	ExtraVolumeMounts    []v1.VolumeMount                         `json:"extraVolumeMounts,omitempty"`
}

// CacheServerSpecApplyConfiguration constructs a declarative configuration of the CacheServerSpec type for use with
// apply.
func CacheServerSpec() *CacheServerSpecApplyConfiguration {
	return &CacheServerSpecApplyConfiguration{}
}

// WithClusterDomain sets the ClusterDomain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterDomain field is set to the value of the last call.
func (b *CacheServerSpecApplyConfiguration) WithClusterDomain(value string) *CacheServerSpecApplyConfiguration {
	b.ClusterDomain = &value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *CacheServerSpecApplyConfiguration) WithImage(value *ImageSpecApplyConfiguration) *CacheServerSpecApplyConfiguration {
	b.Image = value
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *CacheServerSpecApplyConfiguration) WithReplicas(value int32) *CacheServerSpecApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithLogging sets the Logging field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Logging field is set to the value of the last call.
func (b *CacheServerSpecApplyConfiguration) WithLogging(value *LoggingSpecApplyConfiguration) *CacheServerSpecApplyConfiguration {
	b.Logging = value
	return b
}

// WithCertificates sets the Certificates field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Certificates field is set to the value of the last call.
func (b *CacheServerSpecApplyConfiguration) WithCertificates(value *CertificatesApplyConfiguration) *CacheServerSpecApplyConfiguration {
	b.Certificates = value
	return b
}

// WithCertificateTemplates sets the CertificateTemplates field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CertificateTemplates field is set to the value of the last call.
func (b *CacheServerSpecApplyConfiguration) WithCertificateTemplates(value operatorv1alpha1.CertificateTemplateMap) *CacheServerSpecApplyConfiguration {
	b.CertificateTemplates = &value
	return b
}

// WithServiceTemplate sets the ServiceTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceTemplate field is set to the value of the last call.
func (b *CacheServerSpecApplyConfiguration) WithServiceTemplate(value *ServiceTemplateApplyConfiguration) *CacheServerSpecApplyConfiguration {
	b.ServiceTemplate = value
	return b
}

// WithDeploymentTemplate sets the DeploymentTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeploymentTemplate field is set to the value of the last call.
func (b *CacheServerSpecApplyConfiguration) WithDeploymentTemplate(value *DeploymentTemplateApplyConfiguration) *CacheServerSpecApplyConfiguration {
	b.DeploymentTemplate = value
	return b
}

// WithEtcd sets the Etcd field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Etcd field is set to the value of the last call.
func (b *CacheServerSpecApplyConfiguration) WithEtcd(value *EtcdConfigApplyConfiguration) *CacheServerSpecApplyConfiguration {
	b.Etcd = value
	return b
}

// WithExtraArgs adds the given value to the ExtraArgs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExtraArgs field.
func (b *CacheServerSpecApplyConfiguration) WithExtraArgs(values ...string) *CacheServerSpecApplyConfiguration {
	for i := range values {
		b.ExtraArgs = append(b.ExtraArgs, values[i])
	}
	return b
}

// WithExtraVolumes adds the given value to the ExtraVolumes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExtraVolumes field.
func (b *CacheServerSpecApplyConfiguration) WithExtraVolumes(values ...v1.Volume) *CacheServerSpecApplyConfiguration {
	for i := range values {
		b.ExtraVolumes = append(b.ExtraVolumes, values[i])
	}
	return b
}

// WithExtraVolumeMounts adds the given value to the ExtraVolumeMounts field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExtraVolumeMounts field.
func (b *CacheServerSpecApplyConfiguration) WithExtraVolumeMounts(values ...v1.VolumeMount) *CacheServerSpecApplyConfiguration {
	for i := range values {
		b.ExtraVolumeMounts = append(b.ExtraVolumeMounts, values[i])
	}
	return b
}
