/*
Copyright 2024 The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen-v0.32. DO NOT EDIT.

package v1alpha1

// EtcdConfigApplyConfiguration represents a declarative configuration of the EtcdConfig type for use
// with apply.
type EtcdConfigApplyConfiguration struct {
	Endpoints []string                         `json:"endpoints,omitempty"`
	TLSConfig *EtcdTLSConfigApplyConfiguration `json:"tlsConfig,omitempty"`
	Prefix    *string                          `json:"prefix,omitempty"`
}

// EtcdConfigApplyConfiguration constructs a declarative configuration of the EtcdConfig type for use with
// apply.
func EtcdConfig() *EtcdConfigApplyConfiguration {
	return &EtcdConfigApplyConfiguration{}
}

// WithEndpoints adds the given value to the Endpoints field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Endpoints field.
func (b *EtcdConfigApplyConfiguration) WithEndpoints(values ...string) *EtcdConfigApplyConfiguration {
	for i := range values {
		b.Endpoints = append(b.Endpoints, values[i])
	}
	return b
}

// WithTLSConfig sets the TLSConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLSConfig field is set to the value of the last call.
func (b *EtcdConfigApplyConfiguration) WithTLSConfig(value *EtcdTLSConfigApplyConfiguration) *EtcdConfigApplyConfiguration {
	b.TLSConfig = value
	return b
}

// WithPrefix sets the Prefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Prefix field is set to the value of the last call.
func (b *EtcdConfigApplyConfiguration) WithPrefix(value string) *EtcdConfigApplyConfiguration {
	b.Prefix = &value
	return b
}
