/*
Copyright 2024 The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen-v0.32. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"

	operatorv1alpha1 "github.com/kcp-dev/kcp-operator/sdk/apis/operator/v1alpha1"
)

// FrontProxySpecApplyConfiguration represents a declarative configuration of the FrontProxySpec type for use
// with apply.
type FrontProxySpecApplyConfiguration struct {
	RootShard              *RootShardConfigApplyConfiguration       `json:"rootShard,omitempty"`
	Replicas               *int32                                   `json:"replicas,omitempty"`
	Resources              *v1.ResourceRequirements                 `json:"resources,omitempty"`
	Auth                   *AuthSpecApplyConfiguration              `json:"auth,omitempty"`
	AdditionalPathMappings []PathMappingEntryApplyConfiguration     `json:"additionalPathMappings,omitempty"`
	Image                  *ImageSpecApplyConfiguration             `json:"image,omitempty"`
	ExternalHostname       *string                                  `json:"externalHostname,omitempty"`
	External               *ExternalConfigApplyConfiguration        `json:"external,omitempty"`
	ServiceTemplate        *ServiceTemplateApplyConfiguration       `json:"serviceTemplate,omitempty"`
	DeploymentTemplate     *DeploymentTemplateApplyConfiguration    `json:"deploymentTemplate,omitempty"`
	CertificateTemplates   *operatorv1alpha1.CertificateTemplateMap `json:"certificateTemplates,omitempty"`
	CABundleSecretRef      *v1.LocalObjectReference                 `json:"caBundleSecretRef,omitempty"`
	ClientCABundleRef      *v1.LocalObjectReference                 `json:"clientCABundleRef,omitempty"`
	ExtraArgs              []string                                 `json:"extraArgs,omitempty"`
	ExtraVolumes           []v1.Volume                              `json:"extraVolumes,omitempty"`
	ExtraVolumeMounts      []v1.VolumeMount                         `json:"extraVolumeMounts,omitempty"`
	Logging                *LoggingSpecApplyConfiguration           `json:"logging,omitempty"`
}

// FrontProxySpecApplyConfiguration constructs a declarative configuration of the FrontProxySpec type for use with
// apply.
func FrontProxySpec() *FrontProxySpecApplyConfiguration {
	return &FrontProxySpecApplyConfiguration{}
}

// WithRootShard sets the RootShard field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RootShard field is set to the value of the last call.
func (b *FrontProxySpecApplyConfiguration) WithRootShard(value *RootShardConfigApplyConfiguration) *FrontProxySpecApplyConfiguration {
	b.RootShard = value
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *FrontProxySpecApplyConfiguration) WithReplicas(value int32) *FrontProxySpecApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *FrontProxySpecApplyConfiguration) WithResources(value v1.ResourceRequirements) *FrontProxySpecApplyConfiguration {
	b.Resources = &value
	return b
}

// WithAuth sets the Auth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Auth field is set to the value of the last call.
func (b *FrontProxySpecApplyConfiguration) WithAuth(value *AuthSpecApplyConfiguration) *FrontProxySpecApplyConfiguration {
	b.Auth = value
	return b
}

// WithAdditionalPathMappings adds the given value to the AdditionalPathMappings field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AdditionalPathMappings field.
func (b *FrontProxySpecApplyConfiguration) WithAdditionalPathMappings(values ...*PathMappingEntryApplyConfiguration) *FrontProxySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAdditionalPathMappings")
		}
		b.AdditionalPathMappings = append(b.AdditionalPathMappings, *values[i])
	}
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *FrontProxySpecApplyConfiguration) WithImage(value *ImageSpecApplyConfiguration) *FrontProxySpecApplyConfiguration {
	b.Image = value
	return b
}

// WithExternalHostname sets the ExternalHostname field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExternalHostname field is set to the value of the last call.
func (b *FrontProxySpecApplyConfiguration) WithExternalHostname(value string) *FrontProxySpecApplyConfiguration {
	b.ExternalHostname = &value
	return b
}

// WithExternal sets the External field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the External field is set to the value of the last call.
func (b *FrontProxySpecApplyConfiguration) WithExternal(value *ExternalConfigApplyConfiguration) *FrontProxySpecApplyConfiguration {
	b.External = value
	return b
}

// WithServiceTemplate sets the ServiceTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceTemplate field is set to the value of the last call.
func (b *FrontProxySpecApplyConfiguration) WithServiceTemplate(value *ServiceTemplateApplyConfiguration) *FrontProxySpecApplyConfiguration {
	b.ServiceTemplate = value
	return b
}

// WithDeploymentTemplate sets the DeploymentTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeploymentTemplate field is set to the value of the last call.
func (b *FrontProxySpecApplyConfiguration) WithDeploymentTemplate(value *DeploymentTemplateApplyConfiguration) *FrontProxySpecApplyConfiguration {
	b.DeploymentTemplate = value
	return b
}

// WithCertificateTemplates sets the CertificateTemplates field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CertificateTemplates field is set to the value of the last call.
func (b *FrontProxySpecApplyConfiguration) WithCertificateTemplates(value operatorv1alpha1.CertificateTemplateMap) *FrontProxySpecApplyConfiguration {
	b.CertificateTemplates = &value
	return b
}

// WithCABundleSecretRef sets the CABundleSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CABundleSecretRef field is set to the value of the last call.
func (b *FrontProxySpecApplyConfiguration) WithCABundleSecretRef(value v1.LocalObjectReference) *FrontProxySpecApplyConfiguration {
	b.CABundleSecretRef = &value
	return b
}

// WithClientCABundleRef sets the ClientCABundleRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientCABundleRef field is set to the value of the last call.
func (b *FrontProxySpecApplyConfiguration) WithClientCABundleRef(value v1.LocalObjectReference) *FrontProxySpecApplyConfiguration {
	b.ClientCABundleRef = &value
	return b
}

// WithExtraArgs adds the given value to the ExtraArgs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExtraArgs field.
func (b *FrontProxySpecApplyConfiguration) WithExtraArgs(values ...string) *FrontProxySpecApplyConfiguration {
	for i := range values {
		b.ExtraArgs = append(b.ExtraArgs, values[i])
	}
	return b
}

// WithExtraVolumes adds the given value to the ExtraVolumes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExtraVolumes field.
func (b *FrontProxySpecApplyConfiguration) WithExtraVolumes(values ...v1.Volume) *FrontProxySpecApplyConfiguration {
	for i := range values {
		b.ExtraVolumes = append(b.ExtraVolumes, values[i])
	}
	return b
}

// WithExtraVolumeMounts adds the given value to the ExtraVolumeMounts field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExtraVolumeMounts field.
func (b *FrontProxySpecApplyConfiguration) WithExtraVolumeMounts(values ...v1.VolumeMount) *FrontProxySpecApplyConfiguration {
	for i := range values {
		b.ExtraVolumeMounts = append(b.ExtraVolumeMounts, values[i])
	}
	return b
}

// WithLogging sets the Logging field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Logging field is set to the value of the last call.
func (b *FrontProxySpecApplyConfiguration) WithLogging(value *LoggingSpecApplyConfiguration) *FrontProxySpecApplyConfiguration {
	b.Logging = value
	return b
}
