/*
Copyright 2024 The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen-v0.32. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"

	operatorv1alpha1 "github.com/kcp-dev/kcp-operator/sdk/apis/operator/v1alpha1"
)

// ShardSpecApplyConfiguration represents a declarative configuration of the ShardSpec type for use
// with apply.
type ShardSpecApplyConfiguration struct {
	CommonShardSpecApplyConfiguration `json:",inline"`
	RootShard                         *RootShardConfigApplyConfiguration  `json:"rootShard,omitempty"`
	Cache                             *ShardCacheConfigApplyConfiguration `json:"cache,omitempty"`
}

// ShardSpecApplyConfiguration constructs a declarative configuration of the ShardSpec type for use with
// apply.
func ShardSpec() *ShardSpecApplyConfiguration {
	return &ShardSpecApplyConfiguration{}
}

// WithClusterDomain sets the ClusterDomain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterDomain field is set to the value of the last call.
func (b *ShardSpecApplyConfiguration) WithClusterDomain(value string) *ShardSpecApplyConfiguration {
	b.CommonShardSpecApplyConfiguration.ClusterDomain = &value
	return b
}

// WithShardBaseURL sets the ShardBaseURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ShardBaseURL field is set to the value of the last call.
func (b *ShardSpecApplyConfiguration) WithShardBaseURL(value string) *ShardSpecApplyConfiguration {
	b.CommonShardSpecApplyConfiguration.ShardBaseURL = &value
	return b
}

// WithEtcd sets the Etcd field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Etcd field is set to the value of the last call.
func (b *ShardSpecApplyConfiguration) WithEtcd(value *EtcdConfigApplyConfiguration) *ShardSpecApplyConfiguration {
	b.CommonShardSpecApplyConfiguration.Etcd = value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *ShardSpecApplyConfiguration) WithImage(value *ImageSpecApplyConfiguration) *ShardSpecApplyConfiguration {
	b.CommonShardSpecApplyConfiguration.Image = value
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *ShardSpecApplyConfiguration) WithReplicas(value int32) *ShardSpecApplyConfiguration {
	b.CommonShardSpecApplyConfiguration.Replicas = &value
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *ShardSpecApplyConfiguration) WithResources(value v1.ResourceRequirements) *ShardSpecApplyConfiguration {
	b.CommonShardSpecApplyConfiguration.Resources = &value
	return b
}

// WithAudit sets the Audit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Audit field is set to the value of the last call.
func (b *ShardSpecApplyConfiguration) WithAudit(value *AuditSpecApplyConfiguration) *ShardSpecApplyConfiguration {
	b.CommonShardSpecApplyConfiguration.Audit = value
	return b
}

// WithAuthorization sets the Authorization field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Authorization field is set to the value of the last call.
func (b *ShardSpecApplyConfiguration) WithAuthorization(value *AuthorizationSpecApplyConfiguration) *ShardSpecApplyConfiguration {
	b.CommonShardSpecApplyConfiguration.Authorization = value
	return b
}

// WithAuth sets the Auth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Auth field is set to the value of the last call.
func (b *ShardSpecApplyConfiguration) WithAuth(value *AuthSpecApplyConfiguration) *ShardSpecApplyConfiguration {
	b.CommonShardSpecApplyConfiguration.Auth = value
	return b
}

// WithKCPVirtualWorkspace sets the KCPVirtualWorkspace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KCPVirtualWorkspace field is set to the value of the last call.
func (b *ShardSpecApplyConfiguration) WithKCPVirtualWorkspace(value v1.LocalObjectReference) *ShardSpecApplyConfiguration {
	b.CommonShardSpecApplyConfiguration.KCPVirtualWorkspace = &value
	return b
}

// WithCertificateTemplates sets the CertificateTemplates field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CertificateTemplates field is set to the value of the last call.
func (b *ShardSpecApplyConfiguration) WithCertificateTemplates(value operatorv1alpha1.CertificateTemplateMap) *ShardSpecApplyConfiguration {
	b.CommonShardSpecApplyConfiguration.CertificateTemplates = &value
	return b
}

// WithServiceTemplate sets the ServiceTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceTemplate field is set to the value of the last call.
func (b *ShardSpecApplyConfiguration) WithServiceTemplate(value *ServiceTemplateApplyConfiguration) *ShardSpecApplyConfiguration {
	b.CommonShardSpecApplyConfiguration.ServiceTemplate = value
	return b
}

// WithDeploymentTemplate sets the DeploymentTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeploymentTemplate field is set to the value of the last call.
func (b *ShardSpecApplyConfiguration) WithDeploymentTemplate(value *DeploymentTemplateApplyConfiguration) *ShardSpecApplyConfiguration {
	b.CommonShardSpecApplyConfiguration.DeploymentTemplate = value
	return b
}

// WithCABundleSecretRef sets the CABundleSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CABundleSecretRef field is set to the value of the last call.
func (b *ShardSpecApplyConfiguration) WithCABundleSecretRef(value v1.LocalObjectReference) *ShardSpecApplyConfiguration {
	b.CommonShardSpecApplyConfiguration.CABundleSecretRef = &value
	return b
}

// WithClientCABundleRef sets the ClientCABundleRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientCABundleRef field is set to the value of the last call.
func (b *ShardSpecApplyConfiguration) WithClientCABundleRef(value v1.LocalObjectReference) *ShardSpecApplyConfiguration {
	b.CommonShardSpecApplyConfiguration.ClientCABundleRef = &value
	return b
}

// WithExtraArgs adds the given value to the ExtraArgs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExtraArgs field.
func (b *ShardSpecApplyConfiguration) WithExtraArgs(values ...string) *ShardSpecApplyConfiguration {
	for i := range values {
		b.CommonShardSpecApplyConfiguration.ExtraArgs = append(b.CommonShardSpecApplyConfiguration.ExtraArgs, values[i])
	}
	return b
}

// WithExtraVolumes adds the given value to the ExtraVolumes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExtraVolumes field.
func (b *ShardSpecApplyConfiguration) WithExtraVolumes(values ...v1.Volume) *ShardSpecApplyConfiguration {
	for i := range values {
		b.CommonShardSpecApplyConfiguration.ExtraVolumes = append(b.CommonShardSpecApplyConfiguration.ExtraVolumes, values[i])
	}
	return b
}

// WithExtraVolumeMounts adds the given value to the ExtraVolumeMounts field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExtraVolumeMounts field.
func (b *ShardSpecApplyConfiguration) WithExtraVolumeMounts(values ...v1.VolumeMount) *ShardSpecApplyConfiguration {
	for i := range values {
		b.CommonShardSpecApplyConfiguration.ExtraVolumeMounts = append(b.CommonShardSpecApplyConfiguration.ExtraVolumeMounts, values[i])
	}
	return b
}

// WithLogging sets the Logging field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Logging field is set to the value of the last call.
func (b *ShardSpecApplyConfiguration) WithLogging(value *LoggingSpecApplyConfiguration) *ShardSpecApplyConfiguration {
	b.CommonShardSpecApplyConfiguration.Logging = value
	return b
}

// WithRootShard sets the RootShard field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RootShard field is set to the value of the last call.
func (b *ShardSpecApplyConfiguration) WithRootShard(value *RootShardConfigApplyConfiguration) *ShardSpecApplyConfiguration {
	b.RootShard = value
	return b
}

// WithCache sets the Cache field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cache field is set to the value of the last call.
func (b *ShardSpecApplyConfiguration) WithCache(value *ShardCacheConfigApplyConfiguration) *ShardSpecApplyConfiguration {
	b.Cache = value
	return b
}
