/*
Copyright 2024 The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen-v0.32. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"

	operatorv1alpha1 "github.com/kcp-dev/kcp-operator/sdk/apis/operator/v1alpha1"
)

// VirtualWorkspaceSpecApplyConfiguration represents a declarative configuration of the VirtualWorkspaceSpec type for use
// with apply.
type VirtualWorkspaceSpecApplyConfiguration struct {
	Target               *VirtualWorkspaceTargetApplyConfiguration         `json:"target,omitempty"`
	External             *ExternalConfigApplyConfiguration                 `json:"external,omitempty"`
	Image                *ImageSpecApplyConfiguration                      `json:"image,omitempty"`
	Command              []string                                          `json:"command,omitempty"`
	InitContainers       []VirtualWorkspaceInitContainerApplyConfiguration `json:"initContainers,omitempty"`
	Replicas             *int32                                            `json:"replicas,omitempty"`
	Resources            *v1.ResourceRequirements                          `json:"resources,omitempty"`
	CertificateTemplates *operatorv1alpha1.CertificateTemplateMap          `json:"certificateTemplates,omitempty"`
	ServiceTemplate      *ServiceTemplateApplyConfiguration                `json:"serviceTemplate,omitempty"`
	DeploymentTemplate   *DeploymentTemplateApplyConfiguration             `json:"deploymentTemplate,omitempty"`
	CABundleSecretRef    *v1.LocalObjectReference                          `json:"caBundleSecretRef,omitempty"`
	ClientCABundleRef    *v1.LocalObjectReference                          `json:"clientCABundleRef,omitempty"`
	KubeconfigSecretRef  *v1.LocalObjectReference                          `json:"kubeconfigSecretRef,omitempty"`
	ExtraArgs            []string                                          `json:"extraArgs,omitempty"`
	ExtraVolumes         []v1.Volume                                       `json:"extraVolumes,omitempty"`
	ExtraVolumeMounts    []v1.VolumeMount                                  `json:"extraVolumeMounts,omitempty"`
	Logging              *LoggingSpecApplyConfiguration                    `json:"logging,omitempty"`
	ClusterDomain        *string                                           `json:"clusterDomain,omitempty"`
}

// VirtualWorkspaceSpecApplyConfiguration constructs a declarative configuration of the VirtualWorkspaceSpec type for use with
// apply.
func VirtualWorkspaceSpec() *VirtualWorkspaceSpecApplyConfiguration {
	return &VirtualWorkspaceSpecApplyConfiguration{}
}

// WithTarget sets the Target field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Target field is set to the value of the last call.
func (b *VirtualWorkspaceSpecApplyConfiguration) WithTarget(value *VirtualWorkspaceTargetApplyConfiguration) *VirtualWorkspaceSpecApplyConfiguration {
	b.Target = value
	return b
}

// WithExternal sets the External field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the External field is set to the value of the last call.
func (b *VirtualWorkspaceSpecApplyConfiguration) WithExternal(value *ExternalConfigApplyConfiguration) *VirtualWorkspaceSpecApplyConfiguration {
	b.External = value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *VirtualWorkspaceSpecApplyConfiguration) WithImage(value *ImageSpecApplyConfiguration) *VirtualWorkspaceSpecApplyConfiguration {
	b.Image = value
	return b
}

// WithCommand adds the given value to the Command field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Command field.
func (b *VirtualWorkspaceSpecApplyConfiguration) WithCommand(values ...string) *VirtualWorkspaceSpecApplyConfiguration {
	for i := range values {
		b.Command = append(b.Command, values[i])
	}
	return b
}

// WithInitContainers adds the given value to the InitContainers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the InitContainers field.
func (b *VirtualWorkspaceSpecApplyConfiguration) WithInitContainers(values ...*VirtualWorkspaceInitContainerApplyConfiguration) *VirtualWorkspaceSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithInitContainers")
		}
		b.InitContainers = append(b.InitContainers, *values[i])
	}
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *VirtualWorkspaceSpecApplyConfiguration) WithReplicas(value int32) *VirtualWorkspaceSpecApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *VirtualWorkspaceSpecApplyConfiguration) WithResources(value v1.ResourceRequirements) *VirtualWorkspaceSpecApplyConfiguration {
	b.Resources = &value
	return b
}

// WithCertificateTemplates sets the CertificateTemplates field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CertificateTemplates field is set to the value of the last call.
func (b *VirtualWorkspaceSpecApplyConfiguration) WithCertificateTemplates(value operatorv1alpha1.CertificateTemplateMap) *VirtualWorkspaceSpecApplyConfiguration {
	b.CertificateTemplates = &value
	return b
}

// WithServiceTemplate sets the ServiceTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceTemplate field is set to the value of the last call.
func (b *VirtualWorkspaceSpecApplyConfiguration) WithServiceTemplate(value *ServiceTemplateApplyConfiguration) *VirtualWorkspaceSpecApplyConfiguration {
	b.ServiceTemplate = value
	return b
}

// WithDeploymentTemplate sets the DeploymentTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeploymentTemplate field is set to the value of the last call.
func (b *VirtualWorkspaceSpecApplyConfiguration) WithDeploymentTemplate(value *DeploymentTemplateApplyConfiguration) *VirtualWorkspaceSpecApplyConfiguration {
	b.DeploymentTemplate = value
	return b
}

// WithCABundleSecretRef sets the CABundleSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CABundleSecretRef field is set to the value of the last call.
func (b *VirtualWorkspaceSpecApplyConfiguration) WithCABundleSecretRef(value v1.LocalObjectReference) *VirtualWorkspaceSpecApplyConfiguration {
	b.CABundleSecretRef = &value
	return b
}

// WithClientCABundleRef sets the ClientCABundleRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientCABundleRef field is set to the value of the last call.
func (b *VirtualWorkspaceSpecApplyConfiguration) WithClientCABundleRef(value v1.LocalObjectReference) *VirtualWorkspaceSpecApplyConfiguration {
	b.ClientCABundleRef = &value
	return b
}

// WithKubeconfigSecretRef sets the KubeconfigSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KubeconfigSecretRef field is set to the value of the last call.
func (b *VirtualWorkspaceSpecApplyConfiguration) WithKubeconfigSecretRef(value v1.LocalObjectReference) *VirtualWorkspaceSpecApplyConfiguration {
	b.KubeconfigSecretRef = &value
	return b
}

// WithExtraArgs adds the given value to the ExtraArgs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExtraArgs field.
func (b *VirtualWorkspaceSpecApplyConfiguration) WithExtraArgs(values ...string) *VirtualWorkspaceSpecApplyConfiguration {
	for i := range values {
		b.ExtraArgs = append(b.ExtraArgs, values[i])
	}
	return b
}

// WithExtraVolumes adds the given value to the ExtraVolumes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExtraVolumes field.
func (b *VirtualWorkspaceSpecApplyConfiguration) WithExtraVolumes(values ...v1.Volume) *VirtualWorkspaceSpecApplyConfiguration {
	for i := range values {
		b.ExtraVolumes = append(b.ExtraVolumes, values[i])
	}
	return b
}

// WithExtraVolumeMounts adds the given value to the ExtraVolumeMounts field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExtraVolumeMounts field.
func (b *VirtualWorkspaceSpecApplyConfiguration) WithExtraVolumeMounts(values ...v1.VolumeMount) *VirtualWorkspaceSpecApplyConfiguration {
	for i := range values {
		b.ExtraVolumeMounts = append(b.ExtraVolumeMounts, values[i])
	}
	return b
}

// WithLogging sets the Logging field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Logging field is set to the value of the last call.
func (b *VirtualWorkspaceSpecApplyConfiguration) WithLogging(value *LoggingSpecApplyConfiguration) *VirtualWorkspaceSpecApplyConfiguration {
	b.Logging = value
	return b
}

// WithClusterDomain sets the ClusterDomain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterDomain field is set to the value of the last call.
func (b *VirtualWorkspaceSpecApplyConfiguration) WithClusterDomain(value string) *VirtualWorkspaceSpecApplyConfiguration {
	b.ClusterDomain = &value
	return b
}
